### ISSUE TITLE
输入密码正确,总是提示:Incorrect Password?

### ISSUE THREAD

**Issue by shw2018** [MikeCoder/hexo-blog-encrypt#101]
如图所示,https://sunhwee.com/posts/ca189e3a.html ,确保密码是输入正确了的.
![2019-08-30 12-05-56 的屏幕截图](https://user-images.githubusercontent.com/37791346/63992515-cf5dd000-cb1e-11e9-90b0-22fe37e57e11.png)

**Comment by xiazeyu** [comment]
CryptoJS未被正确加载(crypto-js.js貌似没有被加载到window上)

**Comment by xiazeyu** [comment]
坐等3.0
还有问题再说吧

**Comment by shw2018** [comment]
> 坐等3.0
> 还有问题再说吧
 我看这个好像加载了的。
![image](https://user-images.githubusercontent.com/37791346/63999135-5fa70f80-cb35-11e9-97fc-0dbb80334d27.png)

**Comment by shw2018** [comment]
> 坐等3.0
> 还有问题再说吧
发现本地生成的时候提示有个warning

![2019-08-30 16-59-32 的屏幕截图](https://user-images.githubusercontent.com/37791346/64007944-b1589580-cb47-11e9-9066-4ac7b077c7fe.png)

**Comment by xiazeyu** [comment]
啊...这个等3.0解决就可以了

**Comment by shw2018** [comment]
> 啊...这个等3.0解决就可以了

3.0啥时候release啊?

**Comment by D0n9X1n** [comment]
快了，估计还有个两到三周吧。(一本正经，仿佛不会跳票。)

你可以在内容里写个 `<p></p>` 来绕过这个坑....

**Comment by shw2018** [comment]
> 快了，估计还有个两到三周吧。(一本正经，仿佛不会跳票。)
> 
> 你可以在内容里写个 `<p></p>` 来绕过这个坑....
:rofl: :rofl:  两三周。。约等于放弃了，，，哈哈哈~

`<p></p>`是放在博客md文章里面？

**Comment by D0n9X1n** [comment]
恩, 就像这样：
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3142935/64024884-fc859f00-cb6d-11e9-8836-2da0db9f22b1.png">

v3.0 主要是 @xiazeyu  在开发，我非常信任他。

**Comment by shw2018** [comment]
> 恩, 就像这样：
> <img alt="image" width="566" src="https://user-images.githubusercontent.com/3142935/64024884-fc859f00-cb6d-11e9-8836-2da0db9f22b1.png">
> 
> v3.0 主要是 @xiazeyu 在开发，我非常信任他。

好的，我试试看。
就是相当于在正文开头加这个标签就行了吧，需不需要把文字内容包裹在标签里面？？

**Comment by D0n9X1n** [comment]
如果你正文有内容的话，那就不会有问题了。

这个报错的情况只出现在正文没有内容的时候。

**Comment by shw2018** [comment]
> 如果你正文有内容的话，那就不会有问题了。
> 
> 这个报错的情况只出现在正文没有内容的时候。

我正文有内容🤣 🤣https://sunhwee.com/posts/ca189e3a.html

**Comment by D0n9X1n** [comment]
你应该用的 [hexo-theme-matery](https://github.com/blinkfox/hexo-theme-matery) 这个主题吧。

我没有重现出来。。。

你有 hexo clean 过吧

**Comment by shw2018** [comment]
> 你应该用的 [hexo-theme-matery](https://github.com/blinkfox/hexo-theme-matery) 这个主题吧。
> 
> 我没有重现出来。。。
> 
> 你有 hexo clean 过吧

是的，我用的matery这个主题，hexo clean  然后hexo g 时会有以下提示：
![image](https://user-images.githubusercontent.com/37791346/64029890-0c09e580-cb78-11e9-9ba9-3701404d8bb9.png)

有时候 hexo s 本地预览输入密码可以，然后部署过后，打开页面输入正确密码，就会提示incorrect password！

摸不着头脑🤣 🤣

**Comment by D0n9X1n** [comment]
[https://mhexo.github.io/2018/06/25/encrypt-test/](https://mhexo.github.io/2018/06/25/encrypt-test/)

密码 123 。。。部署上去也是对的。。

真是头大，明天再看看吧。

**Comment by shw2018** [comment]
> https://mhexo.github.io/2018/06/25/encrypt-test/
> 
> 密码 123 。。。部署上去也是对的。。
> 
> 真是头大，明天再看看吧。

震惊！！为什么你的就可以！问下具体版本和依赖？
这谁顶得住啊。

**Comment by xiazeyu** [comment]
https://github.com/MikeCoder/hexo-blog-encrypt/issues/101#issuecomment-526481495

但是事实是CryptoJS并没有被挂到全局orz..我也不知道发生了什么

https://github.com/MikeCoder/hexo-blog-encrypt/issues/101#issuecomment-526630622

有内容还提示内容为空..
试试hexo g --debug
看看是不是和什么插件冲突了(排除法先测试一下)

**Comment by shw2018** [comment]
> [#101 (comment)](https://github.com/MikeCoder/hexo-blog-encrypt/issues/101#issuecomment-526481495)
> 
> 但是事实是CryptoJS并没有被挂到全局orz..我也不知道发生了什么
> 
> [#101 (comment)](https://github.com/MikeCoder/hexo-blog-encrypt/issues/101#issuecomment-526630622)
> 
> 有内容还提示内容为空..
> 试试hexo g --debug
> 看看是不是和什么插件冲突了(排除法先测试一下)

找到问题所在了,原来是和压缩插件冲突了,本地不执行gulp压缩,部署后就可以正常打开,希望3.0解决这个bug!!

**Comment by xiazeyu** [comment]
哦
应该是你gulp配置错误了...导致CryptoJS没有被暴露到window

3.0不会用到CryptoJS, 所以将不会有问题

**Comment by shw2018** [comment]
> 哦
> 应该是你gulp配置错误了...导致CryptoJS没有被暴露到window
> 
> 3.0不会用到CryptoJS, 所以将不会有问题

嗯嗯，那样自然是极好的。

还有一个问题，加密博文解密后，TOC目录内容就没了？？

**Comment by D0n9X1n** [comment]
对，已知问题，和 TOC 会有冲突，这是由于 hexo 机制导致的。不建议使用加密之后还使用 TOC。

另外你可以选择修改主题，参考：[对 TOC 进行加密](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E5%AF%B9-toc-%E8%BF%9B%E8%A1%8C%E5%8A%A0%E5%AF%86) 主要是将 post.content 按照是否加密替换为 post.origin，其次 toc 的 div 的 id 必须要为 toc-div。

**Comment by shw2018** [comment]
> 对，已知问题，和 TOC 会有冲突，这是由于 hexo 机制导致的。不建议使用加密之后还使用 TOC。
> 
> 另外你可以选择修改主题，参考：[对 TOC 进行加密](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E5%AF%B9-toc-%E8%BF%9B%E8%A1%8C%E5%8A%A0%E5%AF%86) 主要是将 post.content 按照是否加密替换为 post.origin，其次 toc 的 div 的 id 必须要为 toc-div。

太麻烦了，还是看看3.0版本吧。

**Comment by D0n9X1n** [comment]
这个问题，光靠加密插件是解决不了的。得主题配合。

BTW, 你为什么不用这个主题自带的加密?
<img width="874" alt="image" src="https://user-images.githubusercontent.com/3142935/64066104-b2bdb700-cc48-11e9-9365-f4771f0f0152.png">

**Comment by shw2018** [comment]
> 这个问题，光靠加密插件是解决不了的。得主题配合。
> 
> BTW, 你为什么不用这个主题自带的加密?
> <img alt="image" width="874" src="https://user-images.githubusercontent.com/3142935/64066104-b2bdb700-cc48-11e9-9365-f4771f0f0152.png">

原主题密码是直接写在页面内的，作者采用SHA256再加密一遍密码，再用这个值当密码，防止别人识破。然而这种方式是伪加密，查看网页的源代码还是可以看到文章的内容。这种方式可以阻挡99.5%的人，但对付懂行的人就不行了，费点心思就能破解。
除了文章,我还拿来加密相册,你可以试试,打开背景图片1,密码:123,https://sunhwee.com/galleries/

**Comment by D0n9X1n** [comment]
这个先关闭了。

**Comment by shw2018** [comment]
> 这个先关闭了。

好的,谢谢啦!
