### ISSUE TITLE
幾個問題

### ISSUE THREAD

**Issue by jerryc127** [MikeCoder/hexo-blog-encrypt#105]
# Issue

## Steps to Reproduce the Problem

1. _
2. _
3. _

## Specifications

(The version of the project, operating system, hardware etc.)

1. 密碼輸入正確后，文章顯示出來
但是這時console會報問題（雖然不影響使用)
![image](https://user-images.githubusercontent.com/16351105/64419108-c5177500-d0ce-11e9-9cce-018a5661dc25.png)

2. js 是對 toc 進行 display: inline 操作，並只對ID toc_div 進行操作
但是我的主題有2個地方顯示toc（手機界面和電腦顯示地方不同），這樣會導致js只對一個#toc_div 進行操作，建議改用判斷class

3. 怎麽覆蓋hexo-blog-encrypt的function? 因爲不想動源文件的關係
想修改59-60行
https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/lib/blog-encrypt.js#59

**Comment by xiazeyu** [comment]
1 坐等3.0坂本更新
2 3.0版本因为hexo给的钩子不够, 若支持toc加密可能导致原文出现在searchdb内, 且不同主题情况差异太大, 故去掉了自带的toc加密功能. 若您想加密toc, 可以自己研究先前别人的解决方案. 我们也提供 诸如 解密后执行原先markdown内js代码的特性. 
3. 不动源文件做不到. 建议等3.0版本发布再看

**Comment by D0n9X1n** [comment]
1. 已在 v2.2.5 修复。
2. 可以尝试在 callback 部分加上自己的代码，v2.x 版本可以看 [Callback](https://github.com/MikeCoder/hexo-blog-encrypt#callback) 这边的代码会在解密成功之后运行，可以避免直接修改源码。
3. 已在 v2.2.5 修复。

**Comment by D0n9X1n** [comment]
@jerryc127 已修改为通过 classname 进行修改，classname 为 `toc-div-class`.

https://github.com/MikeCoder/hexo-blog-encrypt/blob/0e363cab40ca0769828ec95d32d33724861078d3/lib/blog-encrypt.js#L65

**Comment by jerryc127** [comment]
感謝更新
一個小建議
輸入密碼正確后
建議直接顯示文章、
不用跳出彈窗說‘密碼正確’

**Comment by D0n9X1n** [comment]
Demo page 上是 callback 的测试，实际使用是没有弹窗的。

**Comment by jerryc127** [comment]
@MikeCoder
哦哦
因爲
我在本地http://localhost:4000 測試
有彈窗

**Comment by jerryc127** [comment]
那個 應該是bug
沒看清楚彈窗文字
寫的是 ‘錯誤密碼’
但是 密碼是對了
![image](https://user-images.githubusercontent.com/16351105/64484567-7db3f480-d246-11e9-8f76-c5307d64ba0b.png)

**Comment by jerryc127** [comment]
![image](https://user-images.githubusercontent.com/16351105/64484570-98866900-d246-11e9-9165-9d270e399cd1.png)
