### ISSUE TITLE
2.2.4的问题

### ISSUE THREAD

**Issue by RainEcho** [MikeCoder/hexo-blog-encrypt#106]
1. 在 ReadMe.md 使用说明的高级设置 _config.yml 示例里面选项好像少了个 enable: true ？

2. 在 _config.yml 设置了 abstract、prompt 等选项后加密提示还是显示 The article has been encrypted, please enter your password to view. ，只有在文章头设置才会显示想要的提示。

**Comment by xiazeyu** [comment]
1 这是新版本特性. 坐等版本更新就好了
2 同上
