### ISSUE TITLE
[v3.x 版本] 支持文章维度的 abstract, message 设置

### ISSUE THREAD

**Issue by D0n9X1n** [MikeCoder/hexo-blog-encrypt#107]
版本升级不应损失原有功能。

+ 应改为 _config.yml 中均为默认值，带 default_ 前缀
+ 文章中则可以设置具体值
+ 基础配置命名与 v2.x 版本一致：
    + 显示在博客列表页即 data.abstract 命名为 abstract.
    + 显示在密码输入框前的提示为 message.
    + 模版为 template

**Comment by xiazeyu** [comment]
> 版本升级不应损失原有功能。

嗯, 确实没有损失原有的功能. 只是一开始写的README丢了...然后后来又写了一遍, 可能文档没做好...

> 应改为 config.yml 中均为默认值，带 default 前缀

_config.yml内设置的肯定是默认值, 既然如此那带default我觉得没什么必要. 

> 文章中则可以设置具体值

文章中设置的 abstract, message 等会覆盖掉底层_config.yml中的默认设置
https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/index.js#L81

> 基础配置命名与 v2.x 版本一致：

https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/index.js#L13
之前还在想要不要在_config.yml内支持全局password, 然后我觉得不需要就没写.

**Comment by xiazeyu** [comment]
(主要是因为发了一个小时写的README忘记commit了...然后准备merge conflict的时候不小心就reset掉了...然后心态炸了)

**Comment by xiazeyu** [comment]
要不..你完善一下文档吧orz
