### ISSUE TITLE
[v3.x 版本] 支持 Callback 函数设置

### ISSUE THREAD

**Issue by D0n9X1n** [MikeCoder/hexo-blog-encrypt#108]

**Comment by xiazeyu** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Event/Event

**Comment by xiazeyu** [comment]
其实现在可以解密script标签了以后我觉得这个功能意义不大了...像以前的MathJax现在就可以完美支持...可能以后再加入window_onload和document_DOMContentLoaded的触发支持

**Comment by xiazeyu** [comment]
老的fallback在经历了某些Hexo插件的优化后(UglifyJS或Webpack的包装)可能会导致蜜汁函数作用域问题. 就像

```js

(function a(){balabala;})();
a() // 报错, 找不到a

```

**Comment by D0n9X1n** [comment]
其实这个功能主要是为之后有可能的支持 toc 。。
手动写函数 set display 之类的 （惨）

**Comment by xiazeyu** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/API/Event/Event
用这个吧

其实只是自己插件里用的话...往blog-encrypt.js里怼代码就好了...

TOC么...我觉得要不然就感觉放弃支持, Hexo在这方面做得太垃圾了, 主题的适配也不可能面面俱到
要不然就...想办法把整个.html加密了....
或者用https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-table-of-contents
这个黑科技

**Comment by D0n9X1n** [comment]
怼代码的话，update 一下就一脸黑了。。。


TOC 的话，#105 的提问者就是一个主题开发者。
以后影响大了可以让用户吵着让主题开发者进行适配。

可以约定使用 id 的话，就是 `toc-div`，使用 classname 的话就是 `toc-div-class`。

**Comment by D0n9X1n** [comment]
https://github.com/MikeCoder/hexo-blog-encrypt/blob/6535da25bd166bb8af87e97fc197bcbafff43f6c/index.js#L112

这边的 iv 应该是 16 位吧。

```
Error: Invalid IV length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:95:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:127:20)
    at new Cipheriv (internal/crypto/cipher.js:230:22)
    at Object.createCipheriv (crypto.js:115:10)
    at Hexo.<anonymous> (/Users/Mike/Workspace/hexo-code/test-site/node_modules/hexo-blog-encrypt/index.js:112:25)
    at Hexo.tryCatcher (/Users/Mike/Workspace/hexo-code/test-site/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/Mike/Workspace/hexo-code/test-site/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
```

https://github.com/MikeCoder/hexo-blog-encrypt/blob/6535da25bd166bb8af87e97fc197bcbafff43f6c/index.js#L110

这边第二个 512 应该是 16？


https://github.com/MikeCoder/hexo-blog-encrypt/blob/6535da25bd166bb8af87e97fc197bcbafff43f6c/index.js#L69

应该先加一个判断是否 data.tags 为空。

我本地跑的话，HMAC 校验一直是不过的（T_T)

**Comment by xiazeyu** [comment]
Nodejs和Crypto API中对length单位的定义好像不同..文档没写, 但是我猜一个测出来是bits, 一个是bytes...正好是8倍..所以会有*8, /8这种东西

**Comment by xiazeyu** [comment]
那就把iv改回16位吧..
然后跑不过的话...在这个commit之后不保证能正常用..之后的没测过
https://github.com/MikeCoder/hexo-blog-encrypt/commit/519673862ead693e000799981d6562d7d55dac86

**Comment by xiazeyu** [comment]
data.tags 为undefined...反正我的node没报错..然后我就没管orz

**Comment by D0n9X1n** [comment]
我争取下周末前搞定然后发了，这周太忙了。
