### ISSUE TITLE
提个用户体验的问题

### ISSUE THREAD

**Issue by zhuwenbing** [MikeCoder/hexo-blog-encrypt#110]
# Issue
点击输入密码

## Expected Behavior
点击在文字上即显示密码输入框

## Actual Behavior
点击在文字上不能显示密码输入框，必需是点击在文字四周才行（操作起来感觉很奇怪）。

## Steps to Reproduce the Problem

1. 点击在文字上没有任何反应
2. 点击在文字四周显示密码输入框

## Specifications
(The version of the project, operating system, hardware etc.)
Windows 7, Google Chrome 版本 76.0.3809.132（正式版本） （64 位）

**Comment by D0n9X1n** [comment]
更新到 v3.0.2 即可。
