### ISSUE TITLE
Image failed to display with this plugin

### ISSUE THREAD

**Issue by khoint0210** [MikeCoder/hexo-blog-encrypt#111]
# Issue
After decrypting the article the image not show up
## Expected Behavior
Should show image
## Actual Behavior
Not show up
## Steps to Reproduce the Problem
Not yet
## Specifications
below is the tag without enable plugin
![image](https://user-images.githubusercontent.com/12799726/65066746-2da80100-d9af-11e9-951f-fb67458c2968.png)

below is the tag with an enabled plugin
![image](https://user-images.githubusercontent.com/12799726/65066673-05200700-d9af-11e9-9ce1-4e160e9f8cd1.png)

(The version of the project, operating system, hardware etc.)
I'm using the Hexo theme

**Comment by D0n9X1n** [comment]
Can you provide your theme link on github? Make sure we can reproduce the problem.

It looks like your theme use lazyload to fetch images.

**Comment by khoint0210** [comment]
Oh yes, my theme is using lazyload so it would conflict with this plugin?

**Comment by khoint0210** [comment]
https://nguyentruongkhoi.com/2019/07/12/doi-dieu-ve-macbook-pro-13inch-2019/

password : macbook

**Comment by D0n9X1n** [comment]
Yes, for now. We try to find a good way to support such functionality.

You can add the following code to https://github.com/MikeCoder/hexo-blog-encrypt/blob/1a9073258567a56514cf0363e4f24eafe2ca4482/lib/blog-encrypt.js#L187 for temporary fix.

```
      document.getElementById('hexo-blog-encrypt').appendChild(await convertHTMLToElement(decoded));
      document.getElementById('hexo-blog-encrypt').appendChild(hideButton);

      // add code here
      document.querySelectorAll('img').forEach((elem) => {
        if (elem.getAttribute("data-src") && !elem.src) {
          elem.src = elem.getAttribute('data-src');
        }
      });
      //=======

      // TOC part
      var tocDiv = document.getElementById("toc-div");
      if (tocDiv) {
        tocDiv.style.display = 'inline';
      }

```

**Comment by D0n9X1n** [comment]
Or try to update plugin to v3.0.3.
