### ISSUE TITLE
安装后与live2d插件产生冲突

### ISSUE THREAD

**Issue by kqzh** [MikeCoder/hexo-blog-encrypt#112]
# Issue

## Steps to Reproduce the Problem

yarn add hexo-blog-encrypt
hexo s 
发现原来配置好的live2d出现问题（部分参数失效）
重装多次后还是此问题
’
## Specifications

latest version of hexo-blog-encrypt and hexo-helper-live2d
PC  win10

**Comment by xiazeyu** [comment]
?????

**Comment by kqzh** [comment]
> ?????

hey ！，我发现问题应该在于‘不蒜子统计’与live2d的冲突以及live2d自身的问题（mobile:false不能用）？不是大佬写的插件问题
