### ISSUE TITLE
加密后相对引用的图片不能显示

### ISSUE THREAD

**Issue by ysyluminous** [MikeCoder/hexo-blog-encrypt#116]
我使用了Hexo-abbrlink插件来缩短链接，
图片链接：![1568083268803 ](break_gfw/1568083268803.png)
未使用该插件前，会自动引用相对路径，
http://localhost:4000/posts/812d49a5/1568083268803.png 
是可以正常显示的，
使用该插件后，
http://localhost:4000/posts/812d49a5/break_gfw/1568083268803.png
多了个路径。图片不能正常显示。

**Comment by D0n9X1n** [comment]
感觉像是插件的加载顺序的问题，但是因为 hexo 的插件加载机制无法确定加载顺序，所以没法解决。
