### ISSUE TITLE
测试时发现的问题

### ISSUE THREAD

**Issue by ElfriedeMagdaleneHolger** [MikeCoder/hexo-blog-encrypt#117]
1.config文件中已经配置包括message和abstract在内的相关汉语提示，在某篇文章里只设置了password，结果出来的文章首页简介是那个英文默认版的“此文章已加密”的长句
2.按标签加密到底怎么设置？是在congfig的设置里tagName一栏写上相应的标签名，然后文章头的tags属性里只要含有这一个标签就行？尝试了各种设置方法加密标签都无效啊

**Comment by D0n9X1n** [comment]
1. 本地测试没有出现这个问题，你可以在 `_config.yml`(是 hexo 根目录的 `_config.yml` 不是主题的) 里面给中文加上双引号。

```
encrypt:
    abstract: "该篇文章博主不想让其他人看见哟~"
    message: "点击此处输入正确密码即可阅读本篇文章, 密码均为 hello~"
```

2. 在 `_config.yml` 里面设置:

```
    tags:
        - {name: Encrypted, password: hello}
```

在文章中只要指添加加密的 tag 就好。
```
---
title: CallBack 测试
date: 2019-09-07 16:00:59
tags:
    - Encrypted
---
```

**Comment by ElfriedeMagdaleneHolger** [comment]
经过测试，两个问题都没有解决……第二个我尝试过把分类删除，删除除加密标签外其他标签等方法，均无效，我next版本是7.4.2

**Comment by D0n9X1n** [comment]
emmmm，你直接到 `node_modules/hexo-blog-encrypt` https://github.com/MikeCoder/hexo-blog-encrypt/blob/72e081b3dd67f7d5be4730fe71cc9e96bc176e3c/index.js#L81 代码里打 console.log 看吧，应该是配置出问题了。

最近忙毕业的事，没有多少时间处理相关事务。

**Comment by ElfriedeMagdaleneHolger** [comment]
好的……经过测试可以了……这个加密tag似乎是除了该加密tag别的任何tag都不能打……

**Comment by D0n9X1n** [comment]
恩，我先记下这个 bug，等答辩结束弄。这个 issue 先关掉了。
