### ISSUE TITLE
setup the is error

### ISSUE THREAD

**Issue by nondevops** [MikeCoder/hexo-blog-encrypt#118]
# Issue

## Expected Behavior
hexo 3.9
next 7

## Steps to Reproduce the Problem

1. _ install the result error.

## Specifications
![image](https://user-images.githubusercontent.com/12181410/68073617-e8a82480-fdcc-11e9-83bb-15a1938d9fcb.png)

(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
Do you use the latest version? Can you provide the tags part in your blog?

Seems that your tags part is not an array.

Hexo can parse the header like below, but this plugin only supports array so far.

```
---
title: Test.md
date: 2019-11-03 13:57:49
tags: FFF
---
```
Change to:
```
---
title: Test.md
date: 2019-11-03 13:57:49
tags: 
    - FFF
---
```

**Comment by nondevops** [comment]
> Can you show the tags part in your blog?
> 
> Seems that your tags part is not an array.
> 
> Hexo can parse the header like below, but this plugin only supports array so far.
> 
> ```
> ---
> title: Test.md
> date: 2019-11-03 13:57:49
> tags: FFF
> ---
> ```
> 
> Change to:
> 
> ```
> ---
> title: Test.md
> date: 2019-11-03 13:57:49
> tags: 
>     - FFF
> ---
> ```
> 
> Will fix in next version.

@MikeCoder  This is what I set up before installing this plug-in,And I'm having a problem installing this plug-in, not deploying and publishing it

![image](https://user-images.githubusercontent.com/12181410/68081073-e84a7080-fe42-11e9-9aef-c351ad097962.png)

**Comment by D0n9X1n** [comment]
Weird, I can't reproduce this on my computer,  it shouldn't run the plugin when installing.

Also, you can install the plugin manually.

+ go to `node_modules` folder, and run `git clone https://github.com/MikeCoder/hexo-blog-encrypt.git`
+ add ` "hexo-blog-encrypt": "^3.0.3",` to `package.json`

Then, add `console.log` to `node_modules/hexo-blog-encrypt/index.js` line 39, like:

```
  if (data.tags) {
    // add log here to find out which blog is wrong.
    console.log(data);
    console.log(data.tags);
    data.tags.forEach((cTag, index) => {
      if(tagEncryptName.includes(cTag.name)){
        password = password || tagEncryptPass[index];
      }
    });
  }
```

It may help.

**Comment by nondevops** [comment]
> Weird, I can't reproduce this on my computer, it shouldn't run the plugin when installing.
> 
> Also, you can install the plugin manually.
> 
> * go to `node_modules` folder, and run `git clone https://github.com/MikeCoder/hexo-blog-encrypt.git`
> * add ` "hexo-blog-encrypt": "^3.0.3",` to `package.json`
> 
> Then, add `console.log` to `node_modules/hexo-blog-encrypt/index.js` line 39, like:
> 
> ```
>   if (data.tags) {
>     // add log here to find out which blog is wrong.
>     console.log(data);
>     console.log(data.tags);
>     data.tags.forEach((cTag, index) => {
>       if(tagEncryptName.includes(cTag.name)){
>         password = password || tagEncryptPass[index];
>       }
>     });
>   }
> ```
> 
> It may help.

I think you should test this problem,ths @MikeCoder

**Comment by D0n9X1n** [comment]
For bugs that occur in a specific scenario, debug requires corresponding scenario information. As a developer, you should also be clear that if I can't reproduce it then I can't solve it.

BTW, this is not commercial software.
