### ISSUE TITLE
输入密码后，enter无效

### ISSUE THREAD

**Issue by chengquanzhao** [MikeCoder/hexo-blog-encrypt#119]
# Issue

## Expected Behavior
当我设置完成后，在谷歌浏览器中不好使。在mac自带浏览器中，火狐浏览器中好用。
![image](https://user-images.githubusercontent.com/24383282/68666366-c3f73e00-057e-11ea-9ad5-f6e8a8f0329d.png)
## version
"hexo-blog-encrypt": "^3.0.3"

## Specifications

![image](https://user-images.githubusercontent.com/24383282/68666824-952d9780-057f-11ea-9232-d772a3e960df.png)

**Comment by wwwwwyj** [comment]
你好，请问你解决了吗，我也碰到了一样的问题

**Comment by wwwwwyj** [comment]
原来 closed issue里面有解决，应该是http的问题，改成https就可以了，可能不安全被浏览器拦截了？希望有大神可以解答

**Comment by D0n9X1n** [comment]
大概率是因为 Chrome 已经开始阻止页面加载 http 资源.

英文版新闻: [Google Chrome Will Block Mixed Content](https://www.searchenginejournal.com/google-block-mixed-content-warning/329055/#close)

中文版新闻: [Chrome 将不再允许 https:// 页面加载 HTTP 资源](https://www.oschina.net/news/110345/chrome-to-block-http-in-https)
