### ISSUE TITLE
发现一个小问题

### ISSUE THREAD

**Issue by zhuwenbing** [MikeCoder/hexo-blog-encrypt#12]
图片加密的话，fancybox的弹窗效果将会丢失

**Comment by D0n9X1n** [comment]
这个是因为 fancybox 应该在页面加载的时候注册了 js 函数。对页面的 img 标签做了处理。但是，加密之后的内容是不包含图片标签的，所以没法其效果。

有个临时的解决办法。就是在 [mcommon.js](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/lib/mcommon.js#L20) 的第20行，插入 fancybox 的注册函数。

这个并不是比较通常的情况，所以这边就不放到库里面了。

**Comment by zhuwenbing** [comment]
明白了，多谢
