### ISSUE TITLE
和Hexo的Nexo主题的Tabs功能冲突

### ISSUE THREAD

**Issue by suyinLoong** [MikeCoder/hexo-blog-encrypt#121]
版本：
系统：Windows 10
Hexo：v4.0.0
NexT.Mist： v7.5.0

问题：
使用后导致tabs无法正常显示

Tabs介绍：https://theme-next.org/docs/tag-plugins/tabs

**Comment by D0n9X1n** [comment]
看了下, tab 的实现是在后台渲染的时候, 加密插件在渲染 tab 前就已经执行, 导致 tab 无法被识别. 但是因为 hexo 的插件挂载机制无法设置加载顺序的问题, 该现象目前没有办法解决.
