### ISSUE TITLE
无法生成TOC

### ISSUE THREAD

**Issue by jerryc127** [MikeCoder/hexo-blog-encrypt#122]
# Issue

## Steps to Reproduce the Problem

1. _
2. _
3. _

## Specifications

(The version of the project, operating system, hardware etc.)

hexo版本 4.0.0
主题 butterfly https://github.com/jerryc127/hexo-theme-butterfly

改了TOC
![image](https://user-images.githubusercontent.com/16351105/69980568-71041b80-156b-11ea-890a-02be5063e5e2.png)

设置密码后。toc无法生成。
看了下，有无密码 都是生成了下面一个。。。
似乎 ‘page.encrypt == true’ 这个有无密码都是false的

之前是正常的，不知道什么开始变不行了

**Comment by D0n9X1n** [comment]
升级到 v3.0.4 应该就可以了, 大版本升级的时候, 疏漏了.
