### ISSUE TITLE
加密后hexo-tag-echarts图表不能显示

### ISSUE THREAD

**Issue by wdrich** [MikeCoder/hexo-blog-encrypt#125]
你好，文章加密好hexo-tag-echarts的图表都不能显示。

**Comment by D0n9X1n** [comment]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/3142935/71302689-3e6e7580-23e9-11ea-95f4-715c675724fe.png">

**Comment by D0n9X1n** [comment]
参考:[Callback 中文说明](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E5%85%B3%E4%BA%8E-callback-%E5%87%BD%E6%95%B0)

加 echarts 的函数到文章尾.
