### ISSUE TITLE
Add option to disable logging password?

### ISSUE THREAD

**Issue by ApolloZhu** [MikeCoder/hexo-blog-encrypt#127]
# Issue

Exposes password to CI log.

While knowing which password is used to encrypt each post is a valuable asset, there should be better ways than adding plain text password to console output.

## Expected Behavior

Does not log password or has an option to disable logging password.

## Actual Behavior

Logging password.

## Steps to Reproduce the Problem

1. run `hexo s` or `hexo g`

## Specifications

Since 3.0.0 (6336ccb0bfe61f814fa63641a7cb601320e40954)

**Comment by D0n9X1n** [comment]
It should be fixed in v3.0.9.
