### ISSUE TITLE
Cannot read property 'importKey' of undefined     at getKeyMaterial (blog-encrypt.js:94)

### ISSUE THREAD

**Issue by usench** [MikeCoder/hexo-blog-encrypt#129]
![image](https://user-images.githubusercontent.com/15116442/73856257-230fda80-4870-11ea-9df9-3a8ad316b89e.png)

Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined
    at getKeyMaterial (blog-encrypt.js:94)
    at HTMLDivElement.<anonymous> (blog-encrypt.js:255)

输入正确密码，回车提示js 错误，chrome 版本 79.0.3945.88（正式版本） （64 位）

**Comment by D0n9X1n** [comment]
试试 #128 , #114  看看.

**Comment by usench** [comment]
ok,只能用https 进行访问，免费申请了一个一年的ssl证书，一年之后就收费了 @MikeCoder
