### ISSUE TITLE
页面布局不兼容

### ISSUE THREAD

**Issue by ydx1013** [MikeCoder/hexo-blog-encrypt#13]
![default](https://cloud.githubusercontent.com/assets/15071870/21599319/b9603240-d1a5-11e6-971b-55fc11102c00.png)
你好，麻烦你一下，咨询个问题，这个页面有问题，应该怎么样解决呢？
![image](https://cloud.githubusercontent.com/assets/15071870/21599246/caf18596-d1a4-11e6-9335-d8a3d5f491ec.png)

**Comment by D0n9X1n** [comment]
可以通过修改默认的加密模版实现，[具体的文档](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E4%BF%AE%E6%94%B9%E5%8A%A0%E5%AF%86%E6%A8%A1%E6%9D%BF)
