### ISSUE TITLE
文章加密后文章的目录无法正常加载，如何解决？

### ISSUE THREAD

**Issue by ydteng** [MikeCoder/hexo-blog-encrypt#130]
文章加密后文章的目录无法正常加载，如何解决？

**Comment by D0n9X1n** [comment]
已知问题, 无法解决.

**Comment by ydteng** [comment]
> 已知问题, 无法解决.

还有个问题，给一个页面设置好密码后，然后输入密码正常进入博客，如果修改密码，或者去一个其他不同密码的页面，就会先弹出密码错误的信息框，然后才让重新输入密码，有解决办法吗？😊

**Comment by D0n9X1n** [comment]
emmmmm, 这是个 bug, 我先记下. 周末改一下~

**Comment by D0n9X1n** [comment]
更新到 v3.0.10 试试.

**Comment by ydteng** [comment]
> 更新到 v3.0.10 试试.

我更新到了v3.0.11，不同文章之间的切换已经没问题了，但是同一篇文章修改密码后还是会出现之前那种密码错误的情况，但是这种情况不是很影响使用，毕竟一篇博客不会经常更换密码，但还是希望修复下。😄

**Comment by D0n9X1n** [comment]
后续这种情况就不修复了, 也没法修复, 前端 js 并不能区分密码错还是修改密码后这两种情况.

**Comment by ydteng** [comment]
> 后续这种情况就不修复了, 也没法修复, 前端 js 并不能区分密码错还是修改密码后这两种情况.

好的，谢谢😄
