### ISSUE TITLE
hexo博客加密之后输入密码没反应（https无法解决问题）

### ISSUE THREAD

**Issue by wkzqn** [MikeCoder/hexo-blog-encrypt#131]
# Issue

## Steps to Reproduce the Problem

1. _
2. _
3. _

## Specifications

(The version of the project, operating system, hardware etc.)

**Comment by wkzqn** [comment]
输入密码在谷歌浏览器中有反应，在其它的浏览器中无反应。加入https也在其它浏览器中也没有反应。我的主题是yilia。

**Comment by D0n9X1n** [comment]
1. 安装的加密插件版本号是多少?
2. 是否有其他插件, 是否存在冲突?
3. 其他浏览器是什么浏览器, 什么内核, 什么版本号?
4. 没有反应时 console 中的 log 是什么?
5. 是否能提供一个测试的链接?

**Comment by wkzqn** [comment]
1,版本号为：3.0.12
2.这是装的插件，现在装了个hexo-encrypt，不过最开始的时候我没有装hexo-encrypt，我是在解决不了enter键无反应才装的hexo-encrypt：
![image](https://user-images.githubusercontent.com/44158381/75093453-d1c85080-55bc-11ea-9af1-f5f9694f637a.png)
3.谷歌浏览器enter键有反应，Microsoft Edge浏览器无反应，手机上微信打开也无反应。谷歌浏览器版本：版本 74.0.3729.108（正式版本） （64 位）.
4.不懂控制台，我是hexo的博客。
5.测试用例https://wkzqn.club/2020/02/16/%E6%B5%8B%E8%AF%95/

**Comment by wkzqn** [comment]
插件图片貌似显示不出来，以下是安装的插件：
    "gulp": "^4.0.2",
    "hexo": "^4.0.0",
    "hexo-asset-image": "git+https://github.com/CodeFalling/hexo-asset-image.git",
    "hexo-blog-encrypt": "^3.0.12",
    "hexo-deployer-git": "^2.1.0",
    "hexo-encrypt": "^0.5.5",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"

**Comment by wkzqn** [comment]
hexo的主题是yilia主题

**Comment by D0n9X1n** [comment]
运气好居然测试页面密码 `123` 直接猜出来了= =

按你的测试链接, 实测, 
+ Edge v80.0.361.56 win10 **OK**
+ Firefox 73.0.1 win10 **OK**
+ Edge v80.0.361.57 MacOS **OK**
+ Firefox v73.0.1 MacOS **OK**

PS: 控制台就是按 F12, 然后点 console 看看有没有 log. 

![image](https://user-images.githubusercontent.com/3142935/75093607-3f28b100-55be-11ea-9a23-9d47531033a4.png)

**Comment by D0n9X1n** [comment]
Edge 是 chromium 版本. 手机也试了下, iPhone 下 firefox 和微信都是正常的.

**Comment by wkzqn** [comment]
我发现我的edge的版本是44.18362.449.0，我升级edge之后发现有反应了，不过这个是不是手机端按输入法的回车键没有反应？

**Comment by wkzqn** [comment]
==

**Comment by D0n9X1n** [comment]
iPhone 上我是直接按的 return, 应该类似于回车吧. 

手边没有安卓也没法测..

PS: 考虑下更新成 [Chromium 版本的 Edge](https://www.microsoftedgeinsider.com/en-us/) ? 
虽然 Firefox 是最好的.

**Comment by wkzqn** [comment]
iphone上我按return怎么没有反应呀


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Mike <notifications@github.com&gt;
发送时间: 2020年2月22日 22:15
收件人: MikeCoder/hexo-blog-encrypt <hexo-blog-encrypt@noreply.github.com&gt;
抄送: wkzqn <206878258@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[MikeCoder/hexo-blog-encrypt] hexo博客加密之后输入密码没反应（https无法解决问题） (#131)




iPhone 上我是直接按的 return, 应该类似于回车吧.
 
手边没有安也没法测..
 
PS: 考虑下更新成 Chromium 版本的 Edge ?
 虽然 Firefox 是最好的.

**Comment by D0n9X1n** [comment]
这个就不清楚了. 理论上 iPhone 上输入密码的时候调用的是自带英文输入法, 行为应该是一致的. 

清空下缓存试试?

**Comment by wkzqn** [comment]
你的iPhone是可以的吗？难不成是我ipone的版本太低？我还是ios10.3.3  ==

**Comment by D0n9X1n** [comment]
那应该是....因为使用了 [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API), 可能老版浏览器不支持. 

在这一段说明了:[特性 - 第四条](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E7%89%B9%E6%80%A7)

**Comment by wkzqn** [comment]
我用安卓手机试了一下，发现可以，我的ipone不行⁼⁼


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Mike <notifications@github.com&gt;
发送时间: 2020年2月22日 22:23
收件人: MikeCoder/hexo-blog-encrypt <hexo-blog-encrypt@noreply.github.com&gt;
抄送: wkzqn <206878258@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[MikeCoder/hexo-blog-encrypt] hexo博客加密之后输入密码没反应（https无法解决问题） (#131)




这个就不清楚了. 理论上 iPhone 上输入密码的时候调用的是自带英文输入法, 行为应该是一致的.
 
清空下缓存试试?

**Comment by wkzqn** [comment]
可是我这应该是系统老，不该是浏览器老呀


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Mike <notifications@github.com&gt;
发送时间: 2020年2月22日 22:31
收件人: MikeCoder/hexo-blog-encrypt <hexo-blog-encrypt@noreply.github.com&gt;
抄送: wkzqn <206878258@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[MikeCoder/hexo-blog-encrypt] hexo博客加密之后输入密码没反应（https无法解决问题） (#131)




那应该是....因为使用了 Web Crypto API, 可能老版浏览器不支持.
 
在这一段说明了:特性 - 第四条

**Comment by D0n9X1n** [comment]
(iPhone 上)系统老 = 控件老 = 系统自带组件版本老 = 浏览器内核老 = 浏览器老..

因为苹果的开发政策, 不允许浏览器使用自己的内核, 因而不管是 Chrome 还是 Firefox 都采用的苹果的 Blink 内核.

如果想确保所有浏览器均能使用, 可以使用 v2.2.x 版本, 应该也是个稳定的版本, 文档可以看, [这个旧的版本](https://github.com/MikeCoder/hexo-blog-encrypt/tree/2ca2cbe6071b5f17bc0e7bce3d74bf39c9752dfa) 但是不再提供支持.

**Comment by wkzqn** [comment]
好勒，非常感谢你啦，我的问题解决了😁


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Mike <notifications@github.com&gt;
发送时间: 2020年2月22日 22:40
收件人: MikeCoder/hexo-blog-encrypt <hexo-blog-encrypt@noreply.github.com&gt;
抄送: wkzqn <206878258@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[MikeCoder/hexo-blog-encrypt] hexo博客加密之后输入密码没反应（https无法解决问题） (#131)




系统老 = 控件老 = 系统自带组件版本老 = 浏览器内核老 = 浏览器老..
 
因为苹果的开发政策, 不允许浏览器使用自己的内核, 因而不管是 Chrome 还是 Firefox 都采用的苹果的 Blink 内核.
 
如果想确保所有浏览器均能使用, 可以使用 v2.2.x 版本, 应该也是个稳定的版本, 文档可以看, 这个旧的版本 但是不再提供支持.

**Comment by D0n9X1n** [comment]
既然你也喜欢<鬼灭之刃>, 那就是同道中人了. (滑稽)
