### ISSUE TITLE
一个关于fancybox的小问题

### ISSUE THREAD

**Issue by Clqlq** [MikeCoder/hexo-blog-encrypt#135]
加密含有图片的文章后，图片浏览的 fancybox 效果消失。

搜索过历史 [issue](https://github.com/MikeCoder/hexo-blog-encrypt/issues/12)  
该issue中给出的解决方案貌似现在已经不适用，不知道这个问题现在该如何解决？

打扰了

**Comment by D0n9X1n** [comment]
可以直接在原文中加一段 callback: https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E5%85%B3%E4%BA%8E-callback-%E5%87%BD%E6%95%B0

**Comment by Clqlq** [comment]
明白了，不懂前端，找不到博客主题的那个 callback函数，放弃了

谢谢
