### ISSUE TITLE
加密文章所在index页面显示[object Promise]

### ISSUE THREAD

**Issue by xmzzyo** [MikeCoder/hexo-blog-encrypt#138]
# Issue
在加密文章所在的index页面，会显示[object Promise]。

比如文章在第三页http://localhost:4000/page/3/，则该页为：

![image](https://user-images.githubusercontent.com/35603565/79116442-11403b80-7dbb-11ea-8f9b-396b65b28fd7.png)

若在第一页http://localhost:4000/ ， 则该页为：[object Promise]。

## Steps to Reproduce the Problem

1. _
2. _
3. _

## Specifications

hexo version: 3.9.0 

使用theme为[pure](https://github.com/cofess/hexo-theme-pure)

请问大佬这是为什么。。？

感谢！

(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
应该是和分页插件冲突了, 加密的内容被截断导致解密错误.

不建议开启分页, 在加密的博文上.

**Comment by xmzzyo** [comment]
大佬你好，我设置了不开启分页：
![image](https://user-images.githubusercontent.com/35603565/79179521-61aaae00-7e3a-11ea-821c-b858eab69bf1.png)

然而主页还是[object Promise]。

请问有什么方便的解决方法吗？

谢谢！

**Comment by D0n9X1n** [comment]
试试把主题提到的插件都关掉试试。
https://github.com/cofess/hexo-theme-pure#install-plugin

看上去像那个 json content 插件。

**Comment by xmzzyo** [comment]
你好，都关了还是不行，，这个主题是不是没救了。。

**Comment by D0n9X1n** [comment]
可以试试其他的看看

**Comment by xmzzyo** [comment]
ok，谢了。
