### ISSUE TITLE
一个小bug，加密后图片显示

### ISSUE THREAD

**Issue by Klien-m** [MikeCoder/hexo-blog-encrypt#139]
https://klien-m.github.io/2020/07/01/%E6%97%A0%E9%99%90%E5%88%B6%E7%A5%9E%E8%AF%9D%E8%AF%BB%E5%90%8E/，使用了hexo-blog-encrypt，加密密码是 ’kx12' ,加密输入密码后图片无法正常显示，使用主题为fluid，

**Comment by Klien-m** [comment]
https://klien-m.github.io/2020/07/01/%E6%97%A0%E9%99%90%E5%88%B6%E7%A5%9E%E8%AF%9D%E8%AF%BB%E5%90%8E/

不好意思，链接有点问题，再发一个

**Comment by D0n9X1n** [comment]
两个问题;
1. 图片链接建议使用 https. 原因现在的浏览器大部分为了安全考虑都会拒绝非当前域名的 http 内容, [Google Chrome Will Block Mixed Content](https://www.searchenginejournal.com/google-block-mixed-content-warning/329055/)
2. 这个图片应该使用的额外的插件进行加载, 比较简单的办法就是在博客最后加上一段[回调函数](https://github.com/MikeCoder/hexo-blog-encrypt#about-callback):
```
<script>
    location.reload();
</script>
```

**Comment by Klien-m** [comment]
不好意思，我看说明的时候也看到了回调函数这一段，当时没重视，图片加载不出来的时候，就比较着急

**Comment by D0n9X1n** [comment]
问题解决了嘛？

**Comment by Klien-m** [comment]
我在博文内加入了你给的一段代码
```
<script>
    location.reload();
</script>
```
这段代码导致页面一直刷新，一直跳动。  
然后我按照文档里说的，去找 onload() 的代码，没有找到关于页面加载的代码，我正准备去问fluid主题的开发者呢

**Comment by D0n9X1n** [comment]
23333, 忘了会一直回调 reload。😂。

把回调改成这个：

```
<script>
    Array.prototype.slice.call(document.querySelectorAll('img[srcset]')).forEach(x => x.setAttribute('srcset', x.src));
</script>
```

同时把图片的 http 改成 https。

**Comment by Klien-m** [comment]
可以了，万分感谢
