### ISSUE TITLE
加密后导致原主题微小变形，麻烦帮忙解决以下，十分感谢。

### ISSUE THREAD

**Issue by a89757** [MikeCoder/hexo-blog-encrypt#14]
![003](https://cloud.githubusercontent.com/assets/24940301/21712687/106e2a64-d431-11e6-8e33-3d18fc41fa09.png)

![002](https://cloud.githubusercontent.com/assets/24940301/21712693/167da498-d431-11e6-891d-cb662c02932a.png)

这个导致侧边栏字体变形是什么鬼呢？

**Comment by D0n9X1n** [comment]
你的主题是什么？

**Comment by a89757** [comment]
https://github.com/ppoffice/hexo-theme-icarus

**Comment by D0n9X1n** [comment]
在 `/hexo/themes/icarus/source/css/style.styl` 文件里加入：

```
h3
    font-size: font-size !important
```

比如这样：
```
@import "nib"
@import "_variables"
@import "_util/mixin"
@import "_util/grid"

global-reset()

h3
    font-size: font-size !important

input, button
    margin: 0
    padding: 0
    &::-moz-focus-inner
        border: 0
        padding: 0

html, body, #container
    height: 100%

body
    color: color-default
    background: color-background
    font: font-size font-sans !important
    -webkit-text-size-adjust: 100%
......
```

然后执行 `hexo clean && hexo g && hexo s`


原因，该主题对 `<h3>` 标签的字体设置和 bootstrap.min.css 冲突了。

效果：
![wechatimg19](https://cloud.githubusercontent.com/assets/3142935/21755976/21595520-d656-11e6-92fd-2403ba1ecfb8.jpeg)

**Comment by a89757** [comment]
谢谢大神，感动到哭。
