### ISSUE TITLE
即使输入正确的密码，也是不能恢复已经被隐藏的内容，而且加密的输入框仍然在页面中显示

### ISSUE THREAD

**Issue by jonnzer** [MikeCoder/hexo-blog-encrypt#140]
# Issue
即使输入正确的密码，也是不能恢复已经被隐藏的内容，而且加密的输入框仍然在页面中显示
## Expected Behavior
输入正确的密码，应该隐藏掉输入框，页面只有之前被隐藏的内容，和再次加密的按钮
## Actual Behavior
输入密码后，不能恢复已经被隐藏的内容
## Steps to Reproduce the Problem

1. _页面连接：https://jonnzer.github.io/2020/07/03/test/ 密码是123
2. _ 报错信息：Cannot read property 'innerText' of undefined  blog-encrypt.js:15 第15行的逻辑里会报错。
3. _
<img width="1920" alt="截屏2020-07-11 下午2 40 04 (2)" src="https://user-images.githubusercontent.com/21023707/87218370-8e605a00-c384-11ea-9d05-7985d407e243.png">

## Specifications
hexo-apollo主题，操作系统macbook的macos，chorme浏览器最新版。
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
能提供下脱敏之后的原文嘛?

**Comment by D0n9X1n** [comment]
感觉有个更加简单的办法...要是可以的话把主题换成 https://github.com/MikeCoder/hexo-theme-gandalfr ?
这个主题外观上和 Apollo 基本上是一致的

**Comment by jonnzer** [comment]
> 能提供下脱敏之后的原文嘛?

原文就是
test 
test
test

**Comment by jonnzer** [comment]
> 感觉有个更加简单的办法...要是可以的话把主题换成 https://github.com/MikeCoder/hexo-theme-gandalfr ?
> 这个主题外观上和 Apollo 基本上是一致的

我之前试过换呢，但是解决不了，我再试一次

**Comment by jonnzer** [comment]
谢谢帅气的Mike哈， https://github.com/MikeCoder/hexo-theme-gandalfr 这个主题我再装一次，可以加密了，感恩！！！
