### ISSUE TITLE
提个功能建议，按标签加密的文章，能否指定其中某篇取消加密，但仍旧保留在那个tag下面？

### ISSUE THREAD

**Issue by forliuyifei** [MikeCoder/hexo-blog-encrypt#142]
描述：
- 我已经设置一个标签`dairy`用于加密, 默认密码`privacypassword`
- 但有时我想让dairy标签下面某篇不单属于此标签的文章不被加密
（比如我想在博客写点生活记录，如果有不该泄露的信息，就加个`dairy`的标签用默认密码加密；
可要是写一些无关紧要**毋需加密**的闲言碎语，又同样想放在dairy标签下面，让它直接展示内容，该怎么办？）

现在有个折中的做法:   
- 给这篇无关紧要的dairy头部信息加上
```
password: publicpassword
abstract: 这是一篇半公开博文 密码publicpassword
message: 请输入密码  publicpassword
```
但这样终究不太方便，能加个`password: noneprivacypassword`用于关闭加密的功能吗? 优先级最高.

**Comment by D0n9X1n** [comment]
先更新到 v3.0.13 然后试试 https://github.com/MikeCoder/hexo-blog-encrypt#to-disable-tag-encryption?
