### ISSUE TITLE
css和js输出文件名最好支持自定义

### ISSUE THREAD

**Issue by lolifamily** [MikeCoder/hexo-blog-encrypt#143]
css和js输出文件名最好支持自定义

**Comment by D0n9X1n** [comment]
需求受众较小, 你可以直接修改 https://github.com/MikeCoder/hexo-blog-encrypt/blob/ed01353245349c94fcc5a11ca67b598161e59bc6/index.js#L117 还有 https://github.com/MikeCoder/hexo-blog-encrypt/blob/ed01353245349c94fcc5a11ca67b598161e59bc6/index.js#L121 这边的代码把文件放到自定义的位置

然后修改 https://github.com/MikeCoder/hexo-blog-encrypt/blob/ed01353245349c94fcc5a11ca67b598161e59bc6/index.js#L108 把路径修改为自定义的路径.
