### ISSUE TITLE
博客在本地预览时能够正常使用加密功能，但是部署到云端就失效出错

### ISSUE THREAD

**Issue by HuangGengNan** [MikeCoder/hexo-blog-encrypt#144]
按要求安装好插件设置好密码后，在本地预览博客，能够正常使用加密解密功能。但是将博客部署到coding上时，文章能够被正常加密，但是无法解密，输入密码后按确定没有反应。
![](https://mweb3.oss-cn-shenzhen.aliyuncs.com/img/1.png)

**Comment by D0n9X1n** [comment]
See #137
