### ISSUE TITLE
通过在butterfly主题5.1.1版本使用hexo-blog-encrpyt插件发现文章封面多了一串字符

### ISSUE THREAD

**Issue by qinyunkai** [MikeCoder/hexo-blog-encrypt#147]
通过在butterfly主题5.1.1版本使用hexo-blog-encrpyt插件发现
文章封面会出现一串字符串
![image](https://user-images.githubusercontent.com/34145869/93310991-03925480-f838-11ea-8f42-c1b8f5f2d77b.png)
我用的windows10系统.
浏览器:chrome,Firefox,qqBrowser
我并没有开启butterfly主题的pjax配置

**Comment by D0n9X1n** [comment]
多的字符看上去是加密之后的文章内容，可能主题在加载的时候把 script 标签内的内容放出来了。插件端做不了什么。

简单点处理的话，F12 看看是哪个 div，在那个 id 上加一个 display:none 试试。

**Comment by D0n9X1n** [comment]
https://github.com/jerryc127/hexo-theme-butterfly/blob/25b0c733dc38e5b9b9f807e00040f70ea61b68f1/layout/includes/mixins/post-ui.pug#L74

看 butterfly 代码的话，是截取的正文的一段长度，多以加密的内容就不能很好展现了。同时因为加密，description 也没法通过 `<!--more-->` 弄出来。估计除非改主题的代码，不然你只能设置首页不显示内容了。至于改的话，思路就是拿 article.abstract 而不是 description 或者自己摘要。

**Comment by hxer520** [comment]
我也是相同的问题,请问有没有解决方法呢?

**Comment by D0n9X1n** [comment]
目前没有很好的解决办法，只能具体主题具体修改。
但是让一个人维护所有主题的变化，不太现实，所以就只能靠热爱开源的各位了。
