### ISSUE TITLE
输入密码之后没反应

### ISSUE THREAD

**Issue by shu1qin9** [MikeCoder/hexo-blog-encrypt#149]
输入密码后无反应，诸多问题解决方案也都做了尝试
最新数据包："hexo-blog-encrypt": "^3.0.13",
这个包的“template.html”文件位于“hexo-blog-encrypt\lib”路径下
而且整个“hexo-blog-encrypt”文件都无法检索到“jQuery.js”，这我就很懵了，而且我的页面加载出来以后，同样不存在jquery.js
![image](https://user-images.githubusercontent.com/53843638/95885454-d477f000-0daf-11eb-88d7-69291be19e6d.png)
全程只有这两个js
![image](https://user-images.githubusercontent.com/53843638/95885534-ec4f7400-0daf-11eb-9084-b4d108ff6444.png)

**Comment by shu1qin9** [comment]
目前问题排查已经步入到了“Cannot read property 'importKey' of undefined”，js文档中的“cryptoObj.subtle.importKey”参数报错，该问题应该是Google的自身的问题，正在排查中

**Comment by shu1qin9** [comment]
好吧，确实是谷歌自身浏览器的问题，火狐正常访问，但是谷歌的安全配置不信任这种加解密方式。

**Comment by D0n9X1n** [comment]
#129 , #114

**Comment by shu1qin9** [comment]
> #129 , #114

嗯，昨天已经定位到问题了，我最近去申请一个ssl证书吧，谢谢

**Comment by just-automatic** [comment]
> 好吧，确实是谷歌自身浏览器的问题，火狐正常访问，但是谷歌的安全配置不信任这种加解密方式。

现在火狐也不行了, `This feature is available only in secure contexts (HTTPS)`
