### ISSUE TITLE
把源文件也加密了怎么解密

### ISSUE THREAD

**Issue by suiang** [MikeCoder/hexo-blog-encrypt#15]
加了密码之后， 源文件.md 文件变成了乱码 。禁用密码 发布文件解密了 但是源文件还是乱码。貌似是文件编码变了！

**Comment by D0n9X1n** [comment]
插件并不会加密原 md 文件，只会加密 public 目录下生成的 html 文件。

另外，请提供你的系统，hexo 版本，log 信息，以及加密内容和复现方式。谢谢！

**Comment by suiang** [comment]
抱歉是我搞错了 用记事本打开是乱码。我以为也加了密，换个编辑器打开就没有问题 看了下应该是编码的问题
