### ISSUE TITLE
[Feature] 封裝成function

### ISSUE THREAD

**Issue by nella17** [MikeCoder/hexo-blog-encrypt#150]
# Feature

在過往的 issue(#146,#134,#65) 顯示對於部分加密有使用需求。
目前 hexo-blog-encrypt 的架構是直接變更 hexo 文章中的所有內容，而這種方式無法很好的被其他插件使用或自行增加使用情境。
希望能將加解密的部分封裝成 function，擴展加密內容的使用情境。

## Expected Behavior

我希望可以結合 [markdown-it-container](https://github.com/markdown-it/markdown-it-container) 使用，透過以下的方式對部分內容進行加密。

```markdown
:::encrypt password
encrypted content
:::
```

**Comment by D0n9X1n** [comment]
这样的话, 用户是否需要额外引入 [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it) 插件来达到该效果？如果是的话，可能超出了插件该有的 scope。

核心难点在于，对于部分刷新的页面，非加密部分可能已经执行了主题特有的操作，此时对加密部分进行解密，加密部分需要再执行一遍该操作，比如加载图片或者加特效，对于没有做幂等性的操作，可能会带来不可预知的结果。当然可以指定部分 div 来刷新，不过这样对应的 issue 会多很多，维护难度会大大增加。

个人理解下，hexo 应该是一个轻量级的博客系统，不应该承载过于复杂的业务需求。

**Comment by nella17** [comment]
的確如此，我沒考慮到和主題操作的部分。
我再思考看看可行性如何，謝謝。
