### ISSUE TITLE
解密后文章网易云音乐外链无法加载

### ISSUE THREAD

**Issue by HewKhingLiu** [MikeCoder/hexo-blog-encrypt#152]
# Issue

## Steps to Reproduce the Problem

在没使用加密插件之之前网易云外链是可以显示的，使用加密插件之后网易云外链无法刷新出来请问一下是哪里有问题吗？

## Specifications

(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
不是很明白你的问题。以后提问参考 #68 , 提供有效的重现方式.

我只找到 [https://music.163.com/#/outchain/2/167850/](https://music.163.com/#/outchain/2/167850/) 这种方式生成外链。不知道什么原因是空白:

![image](https://user-images.githubusercontent.com/3142935/96887388-21964900-14b7-11eb-8e6f-9355fa352834.png)

所以盲猜下.
1. Flash 版本不支持。
2. iframe 版本的话，可能是没有加载。可以 F12 定位下 iframe 的 id，然后 console 里面跑一下：
```js
// 比如 iframe 是  <iframe src="1.htm" id="test"></iframe> 
document.getElementById('test').contentWindow.location.reload(true);
```

如果这个代码可行就参考 [About Callback](https://github.com/MikeCoder/hexo-blog-encrypt#about-callback) 加到 callback 里面。
