### ISSUE TITLE
使用插件输入密码报错

### ISSUE THREAD

**Issue by daochen23** [MikeCoder/hexo-blog-encrypt#153]
你好，我使用插件后，无论密码正确与否都会报错
![image](https://user-images.githubusercontent.com/49630946/97799153-2a311100-1c67-11eb-9558-d6ecc4fe7ba1.png)

**Comment by daochen23** [comment]
![image](https://user-images.githubusercontent.com/49630946/97799171-4e8ced80-1c67-11eb-9579-e2ffd1279168.png)
![image](https://user-images.githubusercontent.com/49630946/97799176-5c427300-1c67-11eb-9fd0-8dca14a3483e.png)

**Comment by daochen23** [comment]
然后就是这个图片页面添加tags的话 hexo g的时候会报错

**Comment by D0n9X1n** [comment]
importKey 看 https://github.com/D0n9X1n/hexo-blog-encrypt/issues/114

`hexo g` 报错是什么?

**Comment by daochen23** [comment]
![image](https://user-images.githubusercontent.com/49630946/97801656-40e06380-1c79-11eb-92dd-15bdda710832.png)

**Comment by daochen23** [comment]
我感觉是butterfly主题问题

**Comment by daochen23** [comment]
![image](https://user-images.githubusercontent.com/49630946/97801718-9caaec80-1c79-11eb-90fe-5faf30c4e00b.png)

**Comment by daochen23** [comment]
是不是我的标签不对

**Comment by D0n9X1n** [comment]
试试 https://github.com/jerryc127/hexo-theme-butterfly/issues/21 ,改成:

```
tags: [标签1,标签2,标签3]
```

如果去除插件还是报同样的错, 建议去主题那边提 issue

**Comment by daochen23** [comment]
是主题的问题，我去那边问问
