### ISSUE TITLE
Suggestion: 提供选项关闭 CLI 的额外输出- 'INFO  hexo-blog-encrypt: encrypting {xxx}'

### ISSUE THREAD

**Issue by szhshp** [MikeCoder/hexo-blog-encrypt#155]
文件`index.js` Line 91

能否提供选项关闭 CLI 的输出: 'INFO  hexo-blog-encrypt: encrypting {xxx}'

**Comment by D0n9X1n** [comment]
Upgrade to v3.0.14 and see https://github.com/D0n9X1n/hexo-blog-encrypt#disable-logging
