### ISSUE TITLE
文章加密出现问题

### ISSUE THREAD

**Issue by xiaowoonly** [MikeCoder/hexo-blog-encrypt#156]
# Issue

## Steps to Reproduce the Problem

1. 字数统计功能 的话，那么本文的字数会显得比实际值大(可以忽略);
2. 代码复制脚本失效；
3. 引用代码会超出行；
4. 目录不显示；

## Specifications

(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
#### 提 issue 之前，请务必提供复现方式，log，配置信息等必要信息。良好的 issue 可以节省双方的时间。
*请严格按照模版要求，不明确的 issue 将直接关闭。*

**参考 issue:**

> + [Issue 83](https://github.com/MikeCoder/hexo-blog-encrypt/issues/83)
> + [Issue 68](https://github.com/MikeCoder/hexo-blog-encrypt/issues/68)
