### ISSUE TITLE
wrong_hash_message comes out for wrong passwords on iPadOS 14 Safari and Chrome

### ISSUE THREAD

**Issue by liginity** [MikeCoder/hexo-blog-encrypt#157]
# Issue

When wrong passwords are input, instead of showing the `wrong_pass_message`, the `wrong_hash_message`
comes out on iPadOS Safari and Chrome, and the content is just disordered code,
when visiting posts on the demo website [mhexo.github.io](https://mhexo.github.io/).

## Expected Behavior

`wrong_pass_message` shows up.

## Actual Behavior

`wrong_hash_message` shows up,  and the content is just disordered code.

## Steps to Reproduce the Problem

1.  use iPadOS 14 and Safari to one post of demo website [mhexo.github.io](https://mhexo.github.io/).
2.  type wrong password for a post
3.  `wrong_hash_message` shows up.

## Specifications

iPadOS 14, Safari or Chrome.

**Comment by D0n9X1n** [comment]
Confirm this bug. Looks like when giving a wrong password, `cryptoObj.subtle.decrypt` will try to continue instead of throwing a exception on Safari and Chrome. 

Fix should be in this week.

**Comment by D0n9X1n** [comment]
Online demo has been updated, and you can try it again.

**Comment by liginity** [comment]
It is ok now with iPadOS 14 Safari and Chrome about the `wrong_pass_message`.

I notice that the post [empty password](https://mhexo.github.io/2020/12/06/Empty-Password-Test/) now has no encryption effect.

**Comment by D0n9X1n** [comment]
Technically, this is as expacted. If a user doesn't set a password, then we should think that user has no intention to encrypt it.
