### ISSUE TITLE
加密后的文章内的js脚本失效以及动态效果丢失

### ISSUE THREAD

**Issue by BytePrince** [MikeCoder/hexo-blog-encrypt#158]
## 具体表现：
1.使用该插件加密文章，输入密码解密文章，解密后显示的文章内的代码块复制按钮会消失，需要**刷新**一下解密后的文章页面才可以正常显示代码块的复制按钮。
2.记得之前在旧版本Hexo（大概是4.2.0）使用的时候，在密码输入框处鼠标悬停还是单击（记不太清了）会有**动态效果**，当前版本丢失了动态效果。
## 本人环境
hexo: 5.2.0
hexo-cli: 4.2.0
os: Windows_NT 10.0.18363 win32 x64
node: 14.15.1
v8: 8.4.371.19-node.17
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 83
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
**Theme**
Hexo 7.8.0

**Comment by D0n9X1n** [comment]
1. 这个是已知的冲突问题，光靠插件没有办法解决。你看看是否能找到代码块部分 onload 时执行的函数，然后在[callback 里面](https://github.com/D0n9X1n/hexo-blog-encrypt#about-callback)重写一下。可以参考 [Callback Test](https://mhexo.github.io/2020/12/06/Callback-Test/)
2. 试试看 [Callback Test](https://mhexo.github.io/2020/12/06/Callback-Test/) 里面是否存在动态效果，如果有的话，你可以先删掉 _config.yml 中的 template 项目，然后在 hexo g 试试。如果没有配置，可能有冲突或者浏览器兼容问题。得再确认下。

**Comment by D0n9X1n** [comment]
确认了第二个问题，不过准备开发模板主题功能，请期待 v3.1.0 吧 #159
