### ISSUE TITLE
安装后 hexo 部署报错

### ISSUE THREAD

**Issue by zbttl** [MikeCoder/hexo-blog-encrypt#163]
## 复现方法
安装后使用 `hexo clean&&hexo g` 即报错：
![image](https://user-images.githubusercontent.com/22035093/104956483-28295380-5a07-11eb-8e7b-4e243c8c29e8.png)
## hexo 环境
>   "hexo": {
    "version": "5.2.0"
  },
  "dependencies": {
    "@next-theme/plugins": "^8.1.0",
    "gitalk": "^1.7.0",
    "gulp": "^4.0.2",
    "hexo": "^5.0.0",
    "hexo-autonofollow": "^1.0.1",
    "hexo-blog-encrypt": "^3.1.2",
    "hexo-deployer-git": "^2.1.0",
    "hexo-excerpt": "^1.1.6",
    "hexo-filter-github-emojis": "^3.0.4",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.1",
    "hexo-generator-searchdb": "^1.3.3",
    "hexo-generator-sitemap": "^2.1.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-permalink-pinyin": "^1.1.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-renderer-swig": "^1.1.0",
    "hexo-server": "^2.0.0",
    "hexo-symbols-count-time": "^0.7.1",
    "quicklink": "^2.0.0"
  }

**Comment by D0n9X1n** [comment]
贴一下该博客的头信息，看着像你的 tags 部分只设置了一个，没有写成数组的形式。

比如这样的 `tags`

```
---
title: Test.md
date: 2019-11-03 13:57:49
tags: FFF
---
```

改成:
```
---
title: Test.md
date: 2019-11-03 13:57:49
tags: 
    - FFF
---
```

**Comment by zbttl** [comment]
确实是 tag 的问题。
原来的 tags 格式：
![image](https://user-images.githubusercontent.com/22035093/105036738-e4caf580-5a97-11eb-8cc2-8e06e742713f.png)
修改 tag 后能成功部署了。
不过这样我得改好多篇文章的 tag 格式，有些麻烦，不知道有啥便捷的方法一键修改么？

**Comment by D0n9X1n** [comment]
目前没有很好的策略一键修改，参考 hexo 的[官方文档](https://hexo.io/docs/front-matter.html)，标准的 tags 依旧是使用以下的格式。
```
categories:
- Sports
- Baseball
tags:
- Injury
- Fight
- Shocking
```

建议还是改过去吧，可以试试 visual studio code 有没有批量修改的插件？

**Comment by zbttl** [comment]
好吧。谢谢大佬。
