### ISSUE TITLE
HTTP页面无法完整支持

### ISSUE THREAD

**Issue by Aqua-Dream** [MikeCoder/hexo-blog-encrypt#166]
HTTP页面在一些浏览器中无法解密(例如chrome)，参见 #114 #128 #137 #144 #149 #153 

原理应该是在chrome的非安全页面(即非本地的http页面)，[客户端无法获取到SubtleCrypto](https://stackoverflow.com/questions/46468104/how-to-use-subtlecrypto-in-chrome-window-crypto-subtle-is-undefined)。

既然同一个问题出现这么多issue，说明大众对http下的使用需求还是很多的，是否考虑迭代下一个版本，使用第三方js插件来实现解密功能，而非使用浏览器自带功能？好处除了能支持http外，附带也能支持较老的浏览器了。

支持加密的第三方js应该不少，例如这个非常轻量：https://github.com/ricmoo/aes-js

**Comment by D0n9X1n** [comment]
v2.2.* 版本就是基于第三方加密库的，如果 http 是强需求，可以考虑使用 v2.2.* 版本。

**Comment by Aqua-Dream** [comment]
> v2.2.* 版本就是基于第三方加密库的，如果 http 是强需求，可以考虑使用 v2.2.* 版本。

试了下确实可用，谢谢。建议在readme中也补充相关内容。
