### ISSUE TITLE
输入密码后按回车键页面没反应,控制台报错

### ISSUE THREAD

**Issue by small-ora** [MikeCoder/hexo-blog-encrypt#167]
# Issue

## Expected Behavior
加密的博客,输入密码后按回车键就可以查看

## Actual Behavior
加密的博客,输入密码后按回车键页面没反应,控制台报错

## 控制台报错信息
Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined
    at getKeyMaterial (hbe.js:98)
    at HTMLDivElement.<anonymous> (hbe.js:267)

## Steps to Reproduce the Problem

1. 使用hexo驱动博客
2. 使用ayer主题(https://github.com/Shen-Yu/hexo-theme-ayer)
3. 安装hexo-blog-encrypt插件,给tag添加密码
4. 访问加密tag下的文章,输入密码

## Specifications
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-blog-encrypt": "^3.1.4",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-searchdb": "^1.3.3",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3"
  }

(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
#129 #114
