### ISSUE TITLE
链接都变成了蓝色

### ISSUE THREAD

**Issue by zi-done** [MikeCoder/hexo-blog-encrypt#17]
为什么我的所有链接变成蓝色的了，我感觉很莫名
https://zidone.cn/2017/04/21/%E5%8D%9A%E6%96%87%E5%8A%A0%E5%AF%86/

**Comment by D0n9X1n** [comment]
默认的加密模版引入了以下的两个 css 文件。这个可能和你的博客模版有冲突。
```
        <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
```

解决方法就是自定义默认模版：[修改模版教程](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E4%BF%AE%E6%94%B9%E5%8A%A0%E5%AF%86%E6%A8%A1%E6%9D%BF)， 然后删去以上的两个 css 引入。不过之后可能你还要自定义下样式。

**Comment by xmeng1** [comment]
https://github.com/MikeCoder/hexo-blog-encrypt/issues/9

**Comment by D0n9X1n** [comment]
更新代码到 v2.0.*。
