### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by A2Data** [MikeCoder/hexo-blog-encrypt#174]
# Issue

## Steps to Reproduce the Problem

1. 环境如下
hexo: 5.4.0
hexo-cli: 4.2.0
os: Linux 3.10.0-693.el7.x86_64 linux x64
node: 12.22.1
v8: 7.8.279.23-node.46
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 72
nghttp2: 1.41.0
napi: 8
llhttp: 2.1.3
http_parser: 2.9.4
openssl: 1.1.1k
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
2. 加密插件为最新版本

3. 报错日志
function getKeyMaterial(password) {
    let encoder = new TextEncoder();
    return cryptoObj.subtle.importKey(
      'raw',
      encoder.encode(password),
      {
        'name': 'PBKDF2',
      },
      false,
      [
        'deriveKey',
        'deriveBits',
      ]
    );
  }

Uncaught (in promise) TypeError: Cannot read property 'importKey' of undefined

## Specifications

(The version of the project, operating system, hardware etc.)

![image](https://user-images.githubusercontent.com/39373008/126588536-d167c586-eec7-4faa-b674-799aa6caf19e.png)

**Comment by D0n9X1n** [comment]
#129
