### ISSUE TITLE
encrypted posts can be found by hexo-generator-search

### ISSUE THREAD

**Issue by BYJRK** [MikeCoder/hexo-blog-encrypt#178]
# Issue

I installed [hexo-generator-search](https://github.com/wzpan/hexo-generator-search) and found out the encrypted articles can also be found by this search tool by inputing some words appeared in the title or the paragraphs of the encrypted post. Is there any method to avoid this?

**Comment by junqi-lu** [comment]
Hi @BYJRK , I use hexo-theme-next@8.7.1 and installed hexo-generator-searchdb@1.3.4, when I search encrypted articles, only the title shows. Maybe you can try it by following [this](https://github.com/theme-next/hexo-generator-searchdb)
