### ISSUE TITLE
能指定加密文章的部份内容吗？

### ISSUE THREAD

**Issue by goodhelp** [MikeCoder/hexo-blog-encrypt#179]
#能不能添加密文章的指定内容

比如只加密一篇文章的指定部份，现在是全部加密，不输入密码就一点看不见文章内容，我希望让文章显示一部分，剩余一部份输入密码才可见，而不是全部不可见!

谢谢!

**Comment by D0n9X1n** [comment]
#134 不行！
谢谢！
