### ISSUE TITLE
输入密码按回车不知为何没反应。

### ISSUE THREAD

**Issue by halohoop** [MikeCoder/hexo-blog-encrypt#18]
输入密码按回车不知为何没反应。

**Comment by D0n9X1n** [comment]
这个需要结合你的博客模版具体内容才好进行判断。
方便说下你的模版吗？

**Comment by D0n9X1n** [comment]
```
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
```
引用了第三方的 jquery 文件，可能你的网络问题，没能加载到这个 js 文件。

**Comment by hoochanlon** [comment]
奇怪了chrome回车无效，edge、opera居然可以...

**Comment by yuchen97** [comment]
我现在解决了，我在这里
https://cdnjs.com/libraries/jquery/1.11.3
找了之前的渲染版本，他的链接貌似做了改动。
我将template里

<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
改成下面这个

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
就ok了

**Comment by loremwalker** [comment]
跟浏览器有一些关系

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
