### ISSUE TITLE
加密之后无法使用Hexo 搜索框

### ISSUE THREAD

**Issue by zhzzy** [MikeCoder/hexo-blog-encrypt#181]
# Issue
在加密之后没有办法在搜索框里面搜索到对应的内容了，而搜索功能是个人觉得Blog很重要的一个功能，所以是否可以将这个改掉?谢谢。

## Expected Behavior
搜索功能是个人觉得Blog很重要的一个功能，所以是否可以将这个改掉，具体就是还是加密了，但是在搜索框里面搜索关键字还是可以搜索到内容。

## Steps to Reproduce the Problem
Easy to reproduce.

**Comment by D0n9X1n** [comment]
hexo 提供的接口有限, 此功能无法通过通用插件形式实现,

同时将加密内容暴露到 search 中, 这种本身就不安全, 尤其是 hexo 纯前端页面, 将 search index 暴露到前端等于不加密.
