### ISSUE TITLE
文章预览界面显示乱码

### ISSUE THREAD

**Issue by seatoro** [MikeCoder/hexo-blog-encrypt#186]
# Issue

文章预览界面显示的不是汉字，而是一堆乱码，如下：
d5362e6b2f922d556e5d1d7d69a2bda353549f89c785115ae0eaeb2e5fae69215f364b8008128aae36b04cfe5dcdcc6cadfcb94830004c8ca5897338ed4ca9e3e4ae1ed7a0f933858e23e9e2ced5044e17635efc86a1ea05a24de0882c72455d87dfc477dc8a90d99699e462673743a72104ac2968bf04367c9f723fd9b75091abd125d600ae6c24fec4bda67ebfefb388a31f8d088a17ae9ac552312eb3282f75d180d58218c7c9da746f97d4de2d88173b864ede91b25493393bf1ae4854c73117919ea845cf8d4334bedbc7b6c9aa2d23f70290887b5a0c649386ed76f2d51c039caa6feffd0a85aa77057d1c80bd256554812d6c262c7...

## Steps to Reproduce the Problem
``` hexo clean && hexo g && hexo s 也没用。


## Specifications
``` hexo: 5.4.1
hexo-cli: 4.3.0
os: win32 10.0.17763
node: 16.13.2
v8: 9.4.146.24-node.14
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

网上查了查，没解决，希望可以回复一下，谢谢！！

**Comment by D0n9X1n** [comment]
提 issue 之前，请务必提供复现方式，log，配置信息等必要信息。良好的 issue 可以节省双方的时间。

请严格按照模版要求，不明确的 issue 将直接关闭。
