### ISSUE TITLE
移动端safari无法访问

### ISSUE THREAD

**Issue by wkmyws** [MikeCoder/hexo-blog-encrypt#187]
# Issue
这是一个很诡异的问题

## Expected Behavior
或许可以加一个按钮代替回车键

## Actual Behavior
当我执行`hexo s`时，电脑端chrome输入密码按下回车可以正常运行，但移动端的safari输入密码后按屏幕键盘上的回车没有任何反应

当我执行`hexo g`并部署后，移动端的safari可以正常运行

## Steps to Reproduce the Problem

1. 执行hexo
2. 打开ipad/iphone端safari，输入密码访问帖子

**Comment by wkmyws** [comment]
又测试了下，部署后也无法访问，
我猜测可能是插件冲突了
hexo-abbrlink
hexo-filter-link-post

**Comment by X2ISPANDA** [comment]
请问您是怎么解决的呢

**Comment by HaoqinChen** [comment]
你好，我也出现在移动端无法回车的问题，请问你最后如何解决呢？
