### ISSUE TITLE
加密后文章目录导航没有了，变成了一句“Please enter the password to read the blog”

### ISSUE THREAD

**Issue by halohoop** [MikeCoder/hexo-blog-encrypt#19]
加密后文章目录导航没有了，变成了一句“Please enter the password to read the blog”

**Comment by D0n9X1n** [comment]
目录导航这部分需要修改你的模版文件：
可以参考：[https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc](https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc)
