### ISSUE TITLE
你好大佬，想请你帮我看下回调函数

### ISSUE THREAD

**Issue by GC-ZF** [MikeCoder/hexo-blog-encrypt#190]
# Issue

文章用了另一个插件hexo-tag-dplayer，在不设置password时加载正常，如果设置了password
```
{% dplayer "url=xxx" "autoplay=false" %}
```
不能够显示出来

## Expected Behavior
预期
![image](https://user-images.githubusercontent.com/94956933/181867555-a8b2d540-7ad0-4544-b955-a5ec3c0469d1.png)

## Actual Behavior
加了密码，dplayer无法使用，暂时用iframe代替了
![image](https://user-images.githubusercontent.com/94956933/181866914-5a21545e-5ce1-44be-bdd3-7ee66ad26cb8.png)
![image](https://user-images.githubusercontent.com/94956933/181867551-b4bc5320-ca0a-4d6b-9427-ffc978e109e4.png)

## Steps to Reproduce the Problem

无密码网址 [https://zhangshier.vip/posts/47314/](https://zhangshier.vip/posts/47314/)

有密码网址 [https://zhangshier.vip/posts/40406/](https://zhangshier.vip/posts/40406/)

## Specifications

(The version of the project, operating system, hardware etc.)
hexo: ^6.2.0
主题：butterfly：4.3.0
hexo-tag-dplayer: ^0.3.3
hexo-blog-encrypt: ^3.1.6
电脑：win10，浏览器：Edge，加密后dplayer无法显示
手机：华为note，浏览器华为自带，加密或不加密，网页过几秒再刷新就有dplayer了(应该是dplayer自身问题)

## 尝试

在之前看过一些别人的提问，通过在文章底部加入回调函数解决(看过readme了，我太弱了，没弄出来)，如果加了密码，这个就会404

![image](https://user-images.githubusercontent.com/94956933/181870222-9b98347e-87d6-441d-80b6-c97f924efb9a.png)

可以帮我看看怎么加么？谢谢大佬

**Comment by GC-ZF** [comment]
麻烦作者了，解决俩插件冲突

影响不是特别大，iframe不能设置禁止自动播放，vidoe可以设置但是width只能设置视频属性，外边框很大一块空白，所以想用dplay插件，如果无解就close掉吧，我用标签吧

**Comment by D0n9X1n** [comment]
看了下 hexo-tag-dplayer 的实现原理, 这种需要在 hexo g 和前端页面间配合的插件比较难兼容.如果能有其他方式绕过就绕过吧.
只能说, hexo 作为纯静态博客系统, 局限还是太大了.
