### ISSUE TITLE
文章预览页显示乱码

### ISSUE THREAD

**Issue by hxer520** [MikeCoder/hexo-blog-encrypt#191]
# Issue
文章预览页显示乱码
## Expected Behavior
<img width="368" alt="image" src="https://user-images.githubusercontent.com/12802662/188000675-f3c8c566-d3cb-49b4-99e5-a3d5fb0273db.png">

## Actual Behavior
<img width="708" alt="image" src="https://user-images.githubusercontent.com/12802662/188000640-c44d273e-10f5-43df-82c8-b4263451296b.png">

## Steps to Reproduce the Problem

1. 插件安装方式按照文档用npm安装的
2. 问题网址网址为:yuices.ml,主题 为butterfly4.4

## Specifications

(The version of the project, operating system, hardware etc.)
<img width="873" alt="image" src="https://user-images.githubusercontent.com/12802662/188000540-d2131ff7-31f2-452f-bc6e-f4ced387b9d3.png">
-----------
尽可能的讲清楚自己的配置和情况了,英语界面有点看不太懂....

**Comment by D0n9X1n** [comment]
Reply in #147
