### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dc932dc** [MikeCoder/hexo-blog-encrypt#192]

**Comment by D0n9X1n** [comment]
已知问题，请参考：[对 TOC 进行加密](https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E5%AF%B9-toc-%E8%BF%9B%E8%A1%8C%E5%8A%A0%E5%AF%86)。

**Comment by D0n9X1n** [comment]
抱歉，最近比较忙。

#58 提供了`next`主题下的解决思路。题主可以按照思路尝试修改。
期待成功之后能反馈社区。
