### ISSUE TITLE
首页加密文章简介部分出现乱码

### ISSUE THREAD

**Issue by dhndzwxj** [MikeCoder/hexo-blog-encrypt#197]
我用的是hexo博客的butterfly主题，使用您提供的插件加密后，首页加密文章的预览部分显示
“ae2fe629905dedfdf32a1e7027a08db046f84b3dd472ac07af5cf6349bde1f2c065a81a8b2087310a446920f3e467e25298431e093ed02fd”
这样的乱码
我的网址是https://www.dhndzwxj.top
麻烦您有时间看一看

**Comment by D0n9X1n** [comment]
这是已知问题，该插件和 butterfly 插件冲突。目前没有很好的解决办法。
