### ISSUE TITLE
输入正确密码，弹出密码错误!!

### ISSUE THREAD

**Issue by Styloer** [MikeCoder/hexo-blog-encrypt#20]

**Comment by D0n9X1n** [comment]
重现方式？

**Comment by Styloer** [comment]
![1](https://user-images.githubusercontent.com/26495648/28146265-16de89b2-67ab-11e7-9717-ea01afc341b7.png)
根据说明设置密码，但是输入密码就提示密码错误！你试一试看，密码为123456[加密文章](http://kongjin.ga/2015/01/03/Mac%E5%B8%B8%E7%94%A8%E8%BD%AF%E4%BB%B6%E5%8F%8A%E5%91%BD%E4%BB%A4/)

**Comment by D0n9X1n** [comment]
插件依赖的 CryptoJS 组件和模版的 requirejs 冲突了。

![c52c03ab-40ca-4897-9d39-fabb68a122d6](https://user-images.githubusercontent.com/3142935/28170879-423efb96-6819-11e7-850d-88348f5be580.png)

建议问下插件作者。然后修改模版的 requireJS 配置。

**Comment by de-conf** [comment]
刚刚试过，你需要这样写password： “密码” 
密码用“”引起

**Comment by vincent27hugh** [comment]
我也遇到了相同情况

**Comment by ghost** [comment]
使用2.0.8版本可以解决此问题：
`npm install hexo-blog-encrypt@2.0.8 --save`
