### ISSUE TITLE
请求增加一个确认按钮

### ISSUE THREAD

**Issue by X2ISPANDA** [MikeCoder/hexo-blog-encrypt#200]
手机端没有回车键无法输入密码。请求增加一个确认按钮。

**Comment by HaoqinChen** [comment]
你好，想请问这个问题最后有解决方法吗?

**Comment by X2ISPANDA** [comment]
把密码框的type改成别的 我忘记我当时改的啥了  反正这样是能解决的

**Comment by HaoqinChen** [comment]
> 把密码框的type改成别的 我忘记我当时改的啥了 反正这样是能解决的

好的，我研究研究，谢谢啦。

**Comment by QiqiXian** [comment]
支持，如果同时开启了Valine评论，回车会跳到评论区，无法解密。

**Comment by bianyukun1213** [comment]
可以写一个 injector，向页面注入一段脚本。这个注入的脚本将 `.hbe-input-field` 的 `enterkeyhint` 属性设为 `done` 就可以了。

**Comment by GeekBookx** [comment]
> 把密码框的type改成别的 我忘记我当时改的啥了 反正这样是能解决的

能具体说说密码框的type是什么意思吗？这个type是指主题么

**Comment by X2ISPANDA** [comment]
h5元素 button的type

**Comment by X2ISPANDA** [comment]
> > 把密码框的type改成别的 我忘记我当时改的啥了 反正这样是能解决的
> 
> 能具体说说密码框的type是什么意思吗？这个type是指主题么

html元素 button的type

**Comment by GeekBookx** [comment]
> > > 把密码框的type改成别的 我忘记我当时改的啥了 反正这样是能解决的
> > 
> > 
> > 能具体说说密码框的type是什么意思吗？这个type是指主题么
> 
> html元素 button的type

`
      const hideButton = document.createElement('button');
      hideButton.textContent = 'Encrypt again';
      hideButton.type = '';
      hideButton.classList.add("hbe-button");
      hideButton.addEventListener('click', () => {
        window.localStorage.removeItem(storageName);
        window.location.reload();
      });`
是hbe.js里面的这几行么？我不太懂html

**Comment by GeekBookx** [comment]
> > > 把密码框的type改成别的 我忘记我当时改的啥了 反正这样是能解决的
> > 
> > 
> > 能具体说说密码框的type是什么意思吗？这个type是指主题么
> 
> html元素 button的type

`
      const hideButton = document.createElement('button');
      hideButton.textContent = 'Encrypt again';
      hideButton.type = 'button';
      hideButton.classList.add("hbe-button");
      hideButton.addEventListener('click', () => {
        window.localStorage.removeItem(storageName);
        window.location.reload();
      });`
是hbe.js里面的这几行么，我不太懂html

**Comment by GeekBookx** [comment]
> > > 把密码框的type改成别的 我忘记我当时改的啥了 反正这样是能解决的
> > 
> > 
> > 能具体说说密码框的type是什么意思吗？这个type是指主题么
> 
> html元素 button的type

` const hideButton = document.createElement('button');`
` hideButton.textContent = 'Encrypt again';`
` hideButton.type = 'button'; hideButton.classList.add("hbe-button");`
` hideButton.addEventListener('click', () => {`
`     window.localStorage.removeItem(storageName);`
`      window.location.reload();`
`  });`
是hbe.js里面的这几行么，我不太懂html

**Comment by paradoxsugar** [comment]
目前已自行实现，修改hbe.theme.html & hbe.js & css文件，但仍希望官方提供支持
