### ISSUE TITLE
代码块工具栏消失

### ISSUE THREAD

**Issue by X2ISPANDA** [MikeCoder/hexo-blog-encrypt#201]
# Issue
解密以后，代码块的highlight-tools标签不见了，刷新恢复正常
## Expected Behavior
解密以后，代码块的highlight-tools正常显示
## Actual Behavior
解密以后，代码块的highlight-tools不显示
## Steps to Reproduce the Problem

1. 加密带有代码块的文章
2. 解密该文章

## Specifications

(The version of the project, operating system, hardware etc.)

**Comment by luckys-yang** [comment]
怎么样你解决了吗这个问题

**Comment by D0n9X1n** [comment]
It's a known issue, you need to add callback to your posts. Try follow here:
https://github.com/D0n9X1n/hexo-blog-encrypt#about-callback
