### ISSUE TITLE
Length of input is too large in mobile devices.

### ISSUE THREAD

**Issue by anonymouscnuser** [MikeCoder/hexo-blog-encrypt#204]
```
.hbe-input {
	position: relative;
	z-index: 1;
	display: inline-block;
	margin: 1em;
	width: 80%;
	min-width: 400px;
	vertical-align: top;
}
```

`min-width: 400px;`

400px is TOO LARGE for most Android devices or iOS devices. As I know, most devices only have a width between 360px - 395px. 

In addition, the parent of the input `overflow: hidden` seems not working, because it has no restriction of width.

**Comment by D0n9X1n** [comment]
Fix in v3.1.9
