### ISSUE TITLE
npm push was unsuccessful.

### ISSUE THREAD

**Issue by mintfog** [MikeCoder/hexo-blog-encrypt#207]
如图所示，昨天提交的 [PR#206](https://github.com/D0n9X1n/hexo-blog-encrypt/pull/206)，似乎在推送 npm 时发生了异常，导致没有成功推送，辛苦作者闲暇时，再次推送一次，万分感谢✌️

Regarding the figure shown, it seems that an exception occurred during the npm push of the submitted [PR#206](https://github.com/D0n9X1n/hexo-blog-encrypt/pull/206) yesterday, resulting in an unsuccessful push. Kindly, when the author has some leisure time, please request them to reattempt the npm push. Your assistance would be greatly appreciated!✌️

![image](https://github.com/D0n9X1n/hexo-blog-encrypt/assets/40230452/1999b8b4-5736-4b82-896b-64f699343809)

**Comment by D0n9X1n** [comment]
v3.1.8 pushed.
