### ISSUE TITLE
标签加密，能不能让整个该标签页面进行加密，而不是只加密其中的文章？

### ISSUE THREAD

**Issue by 4466** [MikeCoder/hexo-blog-encrypt#209]
即是，比如我加密了【前端】这个标签，当我点击前端标签进去的时候，该页面要输入密码，才能看到该标签下的文章列表，这个功能目前有实现了吗？或者能不能实现呢？

**Comment by D0n9X1n** [comment]
目前没有.
从技术上说都可以实现, 但是已经超出了这个插件的功能范围.

**Comment by loohalh** [comment]
> 目前没有.
> 从技术上说都可以实现, 但是已经超出了这个插件的功能范围.

我也在找类似的功能，你找到了吗
