### ISSUE TITLE
Conflict with other Hexo Plugins

### ISSUE THREAD

**Issue by kiarafbickers** [MikeCoder/hexo-blog-encrypt#21]
## Expected Behavior 

Expected that this plugin would work in conjunction with hexo-tag-twitter when both are used in the same blog post.

package.json:
```
    "hexo-tag-twitter": "^1.0.0",
    "hexo-blog-encrypt": "2.0.*"
```

## Actual Behavior

When the `hexo-tag-twitter` and the `hexo-blog-encrypt` plugin are used, twitter post render in other posts. But in the post that we're trying to encrypt, the encryption works but the twitter posts stop rendering.

## Steps to Reproduce the Problem

  1. Npm install both `hexo-tag-twitter` and  `hexo-blog-encrypt`
  2. Create an encrypted blog post with a twitter post

## Specifications

MacOS with the latest version of both plugins.

**Comment by D0n9X1n** [comment]
Thanks for your report.

You can upgrade **hexo-blog-encrypt** to v2.0.2 to fix this issue by using `npm update`

You can check the result [here :https://mhexo.github.io/example-site/2016/10/26/HexoBlogEncrpyt/](https://mhexo.github.io/example-site/2016/10/26/HexoBlogEncrpyt/).

**Comment by kiarafbickers** [comment]
This fixed the issue. Thanks!
