### ISSUE TITLE
大佬好，请问在什么情况下才会触发wrong_hash_message中的提示语

### ISSUE THREAD

**Issue by w1ndys** [MikeCoder/hexo-blog-encrypt#212]
大佬好，请问在什么情况下才会触发wrong_hash_message中的提示语

**Comment by D0n9X1n** [comment]
极端情况，比如在解密之后，恶意插件添加了新的非你自己写的内容。比如你写了 `ABC` 的文字，加密之后，用户输入密码解密。但是在解密和加密的过程中，如果有恶意攻击的话，会告诉用户内容遭到篡改。
不过你可以认为基本不会发生。
