### ISSUE TITLE
更新版本后TOC不显示了

### ISSUE THREAD

**Issue by zhanglibin1986** [MikeCoder/hexo-blog-encrypt#23]
## Expected Behavior 
我用的next主题，用hexo-blog-encrypt的1.1.*版本时，文章内的TOC能正常显示。

## Actual Behavior
更新2.0.*之后，TOC不能显示了。

## Steps to Reproduce the Problem

  1.  打开博客首页
  1.  进入某一篇文章
  1.  没有侧边栏的目录了

## Specifications
(The version of the project, operating system, hardware etc.)
hexo-blog-encrypt 2.0.*
最新的next

**Comment by D0n9X1n** [comment]
看看这个 [Issue](https://github.com/MikeCoder/hexo-blog-encrypt/issues/16) 能不能解决你的问题。

**Comment by zhanglibin1986** [comment]
@MikeCoder 多谢，亲测好用！
