### ISSUE TITLE
在移动设备上无效

### ISSUE THREAD

**Issue by bescks** [MikeCoder/hexo-blog-encrypt#24]
ipad和android的手机上打开加密网页时输入密码的窗口弹不出来

**Comment by D0n9X1n** [comment]
### 输入密码
![wechatimg2](https://user-images.githubusercontent.com/3142935/33801904-f0537d32-dda4-11e7-91d7-4b1718fd572e.jpeg)
### 密码错误
![wechatimg3](https://user-images.githubusercontent.com/3142935/33801905-f1d352cc-dda4-11e7-9d47-f56e3c422aa1.jpeg)
### 解密成功
![wechatimg4](https://user-images.githubusercontent.com/3142935/33801906-f3926a30-dda4-11e7-8e31-9f3571bb6981.jpeg)

测试设备 Iphone 6， 测试浏览器 微信内置 & Firefox & Safari.

你的具体问题是什么？

**Comment by bescks** [comment]
实在不好意思。我仔细检查了一下，第二次deploy时个人配置有问题，现在没问题了。
