### ISSUE TITLE
(node:16613) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.

### ISSUE THREAD

**Issue by edward-p** [MikeCoder/hexo-blog-encrypt#25]
貌似这个api已经快废弃了

**Comment by D0n9X1n** [comment]
这个 API 貌似是 hexo 在调用吧。需要等 hexo 官方更新了。

**Comment by edward-p** [comment]
@MikeCoder 从npm安装的，里面node_modules里面有hexo-fs，就会优先调用你的旧版hexo-fs，删除之，就会调用hexo下的新版hexo-fs，然后就没这个警告。
