### ISSUE TITLE
Style.css的input-container中width写死为500px

### ISSUE THREAD

**Issue by edward-p** [MikeCoder/hexo-blog-encrypt#26]
导致在移动端显示异常,应改为 `max-width: 500px;`
![screenshot_20171210-233947](https://user-images.githubusercontent.com/7891089/33806529-7d1b691e-de04-11e7-9b52-de609993ac13.png)

![screenshot_20171210-235003](https://user-images.githubusercontent.com/7891089/33806558-e8f2b3c2-de04-11e7-92e0-b26cf68e6ab4.png)

**Comment by D0n9X1n** [comment]
升级到 v2.0.3 即可。

**Comment by edward-p** [comment]
👌
