### ISSUE TITLE
feat: 分文章加密

### ISSUE THREAD

**Issue by xiazeyu** [MikeCoder/hexo-blog-encrypt#30]
- [ ] 最好是文章里如果有password就加密，否则就保留原文

**Comment by BillYang2016** [comment]
呃，现在的版本不就是这样做的吗？

**Comment by D0n9X1n** [comment]
现在的版本是需要读取 _config.yml 的这个配置：

```
# Security
##
encrypt:
    enable: true
```
下一个版本中，这个变为不需配置默认为 true，手动变为 false 时，可以全部取消加密。

**Comment by BillYang2016** [comment]
噢

**Comment by izaktan** [comment]
有个疑问，现在能加密一个页面的部分文字吗，比如像有些论坛那样

**Comment by xiazeyu** [comment]
emmm
应该是可以的..
Markdown里写HTML-tag什么的，然后再扫一遍...但是不知道有没有什么“正规”解析方法
```html
Hello world!
<encrypt password=233333>Hello encrypted world!</encrypt>
```

**Comment by xiazeyu** [comment]
https://www.npmjs.com/package/cheerio

**Comment by YH-Chen** [comment]
我也想知道能否部分加密

**Comment by zhuoyuc** [comment]
如果有latex的话解析似乎不正常？因为latex的加载先后顺序？。。。

**Comment by D0n9X1n** [comment]
@KingSann 是的,这个你可以在 [https://github.com/MikeCoder/hexo-blog-encrypt/blob/9ab36534bf0ca81c5c69488483e71808f4e72bb1/lib/blog-encrypt.js#L50](https://github.com/MikeCoder/hexo-blog-encrypt/blob/9ab36534bf0ca81c5c69488483e71808f4e72bb1/lib/blog-encrypt.js#L50) 加进去 latex 的解析代码。具体的话，要看你的模板了。
