### ISSUE TITLE
fix: 与Hexo-generator-searchdb兼容

### ISSUE THREAD

**Issue by xiazeyu** [MikeCoder/hexo-blog-encrypt#32]
- [ ] Hexo-generator-searchdb

**Comment by darkduckgo** [comment]
同样发现类似的问题, 郁闷了许久...  @xiazeyu 搜索插件好像现在简化为叫`hexo-generator-search`了...
如果同时存在的时候, 所有加密页面不管密码正确与否都会提示密码错误.
但是好在加密功能还是支持的, 也能正常解密, 只不过有很多小问题, 以及控制台报错
报错信息简略一下是:
```javascript
Error: Malformed UTF-8 data 
以及
TypeError : cannot read property 'style' of null  at decrtptAES :49
```
话说希望3.0版也能把cookie里写个简单的预防暴力破解~ 多谢
