### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by izaktan** [MikeCoder/hexo-blog-encrypt#33]
第二步npm安装的时候报错了，那个加在json文件里的句子语法错了？
```
npm ERR! file C:\hexo\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected string in JSON at position 908 while parsing '{
npm ERR!   "name": "hexo-site",
npm ERR!   "version": "0'
npm ERR! File: C:\hexo\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\11747\AppData\Roaming\npm-cache\_logs\2018-02-24T13_21_16_542Z-debug.log

```

**Comment by xiazeyu** [comment]
能贴一下package.json吗
或者还原你刚才的操作，在node中直接输入
`npm install --save hexo-blog-encrypt`

**Comment by izaktan** [comment]
谢谢你，我找到语法问题了，这个问题解决了，但是应用之后是这样子
![image](https://user-images.githubusercontent.com/33599274/36631107-07ae28ee-19ad-11e8-8403-5682f7c99603.png)
应该如何优化代码？

**Comment by D0n9X1n** [comment]
应该是和模板冲突了，列一下你的环境。
下次提 issue 先看下样例。给出重现的方式以及你的环境。

**Comment by izaktan** [comment]
这样子，我更新了代码了，https://blog.txshore.tech/ALresources/     你直接看这里吧，我自己的痕迹比较重

**Comment by izaktan** [comment]
抱歉，我的博客自定义痕迹比较重，代码修改可能工程浩大，我总结了一下，其实只要message和abstract这两个属性工作就能解决我的问题，但是我发现直接在md文件顶上加这两个属性好像没有用

**Comment by D0n9X1n** [comment]
`hexo clean && hexo g && hexo s` 看看呢？
修改之后，最好是 `hexo clean` 一下。

**Comment by izaktan** [comment]
这样做了之后
message: Password              显示出来就说Password了  但是
message: &nbsp;&nbsp;Password    显示出来就还是原来默认的 please enter the password to .....
属性的框是不能加空格代码空格的吗
（我这么做是因为不空格在我的页面上这行message字看起来就挨着白框的边界了了，不太美观）

**Comment by D0n9X1n** [comment]
hexo 文章上部分是 yaml 规范，你可以用 `""` 括起来。不过，也会渲染的时候自动删除空格。
在你的模板的 css 上加上 `label {padding-left:10px;}`.

或者参考 [修改默认模板](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E4%BF%AE%E6%94%B9%E5%8A%A0%E5%AF%86%E6%A8%A1%E6%9D%BF)。将默认模板修改为:
``` 
    default_template:
                    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
                    <div id="security">
                        <div class="input-container">
                            <input type="password" class="form-control" id="pass" placeholder=" {{message}} " />
                            <label for="pass" style="padding-left:10px"> {{message}} </label>
                            <div class="bottom-line"></div>
                        </div>
                    </div>
                    <div id="encrypt-blog" style="display:none">
                        {{content}}
                    </div>
```

**Comment by izaktan** [comment]
好的，谢谢！
