### ISSUE TITLE
v2.0.5 breaks index.js

### ISSUE THREAD

**Issue by AlynxZhou** [MikeCoder/hexo-blog-encrypt#37]
## Actual Behavior
After upgrade to 2.0.5, if shows error of cannot find `$` (jQuery), after I look at the code I think `index.js` is totally wrong...I think you should look at it...

是不是文件放错了，为什么hexo插件的index会用到jQuery？而且我看新的index和之前的一点都不一样。

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
Mistake...

upgrade to v2.0.7 ...

**Comment by AlynxZhou** [comment]
@MikeCoder 我曾经以为只有我自己会疯狂commit，直到我刚才upgrade了一下出了bug，我还以为我主题哪里写错了

**Comment by D0n9X1n** [comment]
在测试环境里改代码，然后直接贴到库里。贴进错了文件真是悲伤。。。
