### ISSUE TITLE
按照步骤设置之后，本地打开页面无论输入的密码正确与否都会提示密码错误。。。

### ISSUE THREAD

**Issue by lsjrepo** [MikeCoder/hexo-blog-encrypt#39]
## Steps to Reproduce the Problem

  1. 配置:
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.6.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-blog-encrypt": "2.0.*"
  }
}
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
console 里面有输出嘛？

**Comment by saiJPlus** [comment]
没有输出
