### ISSUE TITLE
解密后流程图无法显示

### ISSUE THREAD

**Issue by zhoumq** [MikeCoder/hexo-blog-encrypt#40]
解锁后，图形及数学公式无法正常显示
## Expected Behavior 

未锁定时显示：
![image](https://user-images.githubusercontent.com/3118706/40060588-8f2f5066-5889-11e8-9125-d34a7a035da6.png)

## Actual Behavior
解锁后，图形及数学公式无法正常显示：
![image](https://user-images.githubusercontent.com/3118706/40060762-eaefb97c-5889-11e8-8e4e-af21a83a2d35.png)

## Steps to Reproduce the Problem

  1. 安装了<https://github.com/webappdevelp/hexo-filter-mermaid-diagrams>及https://github.com/bubkoo/hexo-filter-flowchart

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
原因都是，他们没有触发渲染函数。

hexo-filter-mermaid-diagrams 插件的话，可以在 [hexo-blog-encrypt/lib/blog-encrypt.js line 52](https://github.com/MikeCoder/hexo-blog-encrypt/blob/9ab36534bf0ca81c5c69488483e71808f4e72bb1/lib/blog-encrypt.js#L52) 插入这些代码：
```
    if (window.mermaid) {
      mermaid.initialize({theme: 'forest'});
    }
```

至于后者，因为他的渲染是在后台执行，且是针对每一个图表进行渲染。[比如这里](https://github.com/bubkoo/hexo-filter-flowchart/blob/f0fb28d45fe95e106b250e3f376f3590fc0acef9/lib/renderer.js#L31)，最好需要他进行修改，给每个图进行 class 标识，不然直接使用 textarea 选择元素，效率不高，然后再上述代码之后加入代码，即解密之后重新触发一次渲染函数。这个需要两边一起修改。

**Comment by zhoumq** [comment]
我对前端和hexo都刚接触，很喜欢这个锁定的功能。但是图形的数学公式对我很重要。希望能够在插件中解决。感谢

**Comment by xiazeyu** [comment]
@MikeCoder
有一个想法
就是暴露一个encrypt函数，其中有一个addAfterEvent(callback(content))方法
这样在主题中可以自定义触发类似的渲染函数
