### ISSUE TITLE
issues on the alerts

### ISSUE THREAD

**Issue by fermidos** [MikeCoder/hexo-blog-encrypt#42]
## Expected Behavior 

when entered the right passwd,  it shows fine words
## Actual Behavior

the message is always  
"Incorrect Password!" no matter the passwd i input is right or wrong

## Steps to Reproduce the Problem

  1. open a encoded blog
  2. enter the passwd

## Specifications
(The version of the project, operating system, hardware etc.)
it is not of the hardware

hexo: 3.7.1
hexo-cli: 1.1.0
os: Windows_NT 10.0.17134 win32 x64
http_parser: 2.8.0
node: 9.11.1
v8: 6.2.414.46-node.23
uv: 1.19.2
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 3
openssl: 1.0.2o
icu: 61.1
unicode: 10.0
cldr: 33.0
tz: 2018c
hexo-blog-encrypt 2.0.*

**Comment by D0n9X1n** [comment]
Can you provide the console log?

**Comment by fermidos** [comment]
可以有中文呀， 那就好办了，  就是输入正确密码之后依然弹出错误提醒， 但是能打开，顺便问一下， 可否设置成密码框而不是密码行。

**Comment by dnfupdatey** [comment]
![new](https://user-images.githubusercontent.com/22900982/41074255-b92491bc-6a39-11e8-9bb6-0f9c20dd2df4.png)

**Comment by fermidos** [comment]
![image](https://user-images.githubusercontent.com/22900982/41074271-ce38f0b6-6a39-11e8-96be-6480b5bb9f77.png)

**Comment by D0n9X1n** [comment]
#41 #20 试试

**Comment by fermidos** [comment]
在移动端尝试， 一样问题，41不符
查看网页console 
Error: Can't make callback from given data
    at USING (MathJax.js:19)
    at Object.Push (MathJax.js:19)
    at Object.Queue (MathJax.js:19)
    at decryptAES (blog-encrypt.js:45)
    at HTMLInputElement.document.getElementById.onkeypress (blog-encrypt.js:99)

这个是和mathjax的冲突吗？谢谢

**Comment by D0n9X1n** [comment]
`npm update` 更新到 v2.0.8 试试。

**Comment by fermidos** [comment]
@MikeCoder  更新之后，成功， 非常感谢～
