### ISSUE TITLE
(node:79590) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.这个问题怎么解决？

### ISSUE THREAD

**Issue by dazkarieh** [MikeCoder/hexo-blog-encrypt#45]
ian root# hexo clean --debug
11:25:37.079 DEBUG Hexo version: 3.7.1
11:25:37.081 DEBUG Working directory: /Users/dazkarieh/Public/ian/
11:25:37.181 DEBUG Config loaded: /Users/dazkarieh/Public/ian/_config.yml
11:25:37.219 DEBUG Plugin loaded: hexo-abbrlink
11:25:37.283 DEBUG Plugin loaded: hexo-autonofollow
11:25:37.320 DEBUG Plugin loaded: hexo-blog-encrypt
(node:79590) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
11:25:37.341 DEBUG Plugin loaded: hexo-deployer-git
11:25:37.342 DEBUG Plugin loaded: hexo-generator-archive

**Comment by D0n9X1n** [comment]
原因：使用的 API 陈旧，需要更新。

暂不影响使用，将会在下版本修复。

**Comment by D0n9X1n** [comment]
See https://github.com/hexojs/hexo/issues/2598.

经过测试，最新版的 hexo + hexo-blog-encrypt 不会出现这个事情。

<img width="707" alt="image" src="https://user-images.githubusercontent.com/3142935/41849405-651e68b2-78b3-11e8-9686-78c42db24bea.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/3142935/41849417-6d3042fa-78b3-11e8-97e5-0a1757eb22b3.png">

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3142935/41849445-93808f3c-78b3-11e8-87d1-6fc8e7d40f7f.png">

**Comment by dazkarieh** [comment]
解决了，我把
/node_modules/hexo-blog-encrypt/node_modules/hexo-fs/lib/fs.js
里面的718行的exports.SyncWriteStream = fs.SyncWriteStream;注释掉就好了。
