### ISSUE TITLE
评论部分如何加密

### ISSUE THREAD

**Issue by hubojing** [MikeCoder/hexo-blog-encrypt#47]
您好，请问如何实现评论区也加密？比如我使用的是valine评论。
谢谢！

**Comment by D0n9X1n** [comment]
通过该插件无法实现。

不过，你可以自己魔改 valine 的 js 代码做一个破解稍微费劲的加密。

进行存储的时候进行加密，然后取回数据的时候解密。然后对加密部分的代码进行混淆。不过，都是在用户的浏览器前端进行，调试一下就出来了，所以要想真正做到加密，还是不可能。

**Comment by hubojing** [comment]
了解了，感谢回复！
