### ISSUE TITLE
gulp的minify-js压缩本插件的两个js文件后输入正确密码弹出密码错误

### ISSUE THREAD

**Issue by 0428** [MikeCoder/hexo-blog-encrypt#48]
用gulp压缩hexo代码后，出现输入密码正确，显示密码错误。当在gulpfile.js文件里除去对本插件的两个js文件压缩后，正常。是否是gulp不支持es6强转es5压缩后出现问题，还是有其问题。

**Comment by xiazeyu** [comment]
能否提供出错的压缩后文件?

**Comment by 0428** [comment]
[blog-encrypt.js](https://u.coka.la/8HHewC.js)
[crypto-js.js](https://u.coka.la/XbOLJ.js)

**Comment by mapxn** [comment]
同样的问题+1，目前我排除了这两个js文件的压缩。
