### ISSUE TITLE
插件不能完美适配NexT的Mist主题

### ISSUE THREAD

**Issue by htharoldht** [MikeCoder/hexo-blog-encrypt#49]
加密之后会影响文章内原本超链接的风格：如鼠标放上后会添加下划线，且文章内有超链接的词都会自动添加Cyan颜色（这不是我想要的效果，且不是我设置的），此外，Valine评论的字体也会变小，还有，顶部菜单栏的阴影效果也会变小（原本也会变成Cyan+下划线的，我修改了一下CSS，但是没有完全解决这个问题）。

想来应该是插件修改了NexT主题的配色以及超链接风格。

此外，还会出现night bright代码风格的颜色出现问题。

[可以见我的博客测试文件](https://htharoldht.com/hello-world/#more)
密码是`password`

又发现了问题。。。sidebar里面的中文TOC在解密后依然无法显示解密后的内容
还有，该插件解密后会影响文章里面的字体大小——本来一级标题应该比文章标题小，然而比文章标题大。

我选择的是NexT主题下的Mist，插件还会影响页面的布局——导致sidebar的边距和文章边距过小

**Comment by stevenjoezhang** [comment]
你的网站上重复加载了jQuery和Bootstrap.min.css，是这个导致的问题。你试试`npm update`升级到最新版本，我用着没问题。这个插件的最新版本看上去不会影响NexT本身的样式。

**Comment by htharoldht** [comment]
> 
> 
> 你的网站上重复加载了jQuery和Bootstrap.min.css，是这个导致的问题。你试试`npm update`升级到最新版本，我用着没问题。这个插件的最新版本看上去不会影响NexT本身的样式。

![default](https://user-images.githubusercontent.com/31093493/50089348-973c8880-0240-11e9-8dd5-db68b7e6172c.png)
图上各个按键基本上变色了
![default](https://user-images.githubusercontent.com/31093493/50089864-f8189080-0241-11e9-914c-790b682edd0f.png)
留言部分的字字号也小了

版本:
>npm -v  6.5.0
>nodejs -v 10.14.2
>hexo-blog-encrypt -v 1.1.12

解密后代码高亮的问题仍然存在
![default](https://user-images.githubusercontent.com/31093493/50090028-68bfad00-0242-11e9-87a0-de24063e63c2.png)

**Comment by stevenjoezhang** [comment]
hexo-blog-encrypt 的最新版本是2.0.10，你到博客目录下执行`npm update`升级试试。样式错乱的原因就是加载了`https://cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css`

**Comment by stevenjoezhang** [comment]
![2018-12-17 9 29 17](https://user-images.githubusercontent.com/16272760/50090286-04511d80-0243-11e9-9902-ddec543ac03b.png)
我不确定这些js和css为什么出现在这里……但是移除它们可以解决问题

**Comment by htharoldht** [comment]
@stevenjoezhang  好了, 谢谢. 我卸载了原来的版本, 重新安装才知道我的版本真的过时了

**Comment by stevenjoezhang** [comment]
@htharoldht 解决了就好👍

**Comment by stevenjoezhang** [comment]
你看下边栏啥的是不是也正常了，没问题的话可以把这个https://github.com/theme-next/hexo-theme-next/issues/373 关掉

**Comment by htharoldht** [comment]
@stevenjoezhang  还有一个问题, 解密后目录没了. 那个我马上关

**Comment by stevenjoezhang** [comment]
应该和这个有关：https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#对-toc-进行加密
