### ISSUE TITLE
解密后不支持 hexo-prism-plugin 插件代码高亮美化

### ISSUE THREAD

**Issue by ApollonBar** [MikeCoder/hexo-blog-encrypt#50]
## Expected Behavior 
这个是没加密的效果
![image](https://user-images.githubusercontent.com/25096662/43692782-d1476f7e-995c-11e8-931c-43525ce8b136.png)

## Actual Behavior
这个是加密后解密的效果
![image](https://user-images.githubusercontent.com/25096662/43692749-982a84ec-995c-11e8-923e-d8f82f4be54b.png)

很明显代码高亮失效了，求修复！！！

**Comment by D0n9X1n** [comment]
把 prism 得参数改为 preprocess 试试？

```
prism_plugin:
  mode: 'preprocess'    
```

**Comment by ApollonBar** [comment]
@MikeCoder 没有用噢，默认就是`preprocess`，似乎是加密过的文章解密后都会恢复主题的本身的默认代码样式。不仅仅`prism`会有这个问题，我试过了，是第三方的代码高亮都会失效。

咳～至于这个这么丑的样式。。。是因为我把主题的某个与`prism`冲突的CSS去掉了`margin`，与代码高亮无关
