### ISSUE TITLE
加密之后，输入密码，报错

### ISSUE THREAD

**Issue by shangzekai** [MikeCoder/hexo-blog-encrypt#52]
报如下的错误：

```
Uncaught ReferenceError: decryptAES is not defined
    at HTMLButtonElement.onclick ((index):181)
```

不知道各位大神有没有遇到过的，求解答

**Comment by D0n9X1n** [comment]
`hexo clean` 试一试呢

**Comment by KnorienChang** [comment]
确实无法解密，每次输入密码提示无效的密码。而且也hexo clean先清理过之前的文件了。

**Comment by KnorienChang** [comment]
> 确实无法解密，每次输入密码提示无效的密码。而且也hexo clean先清理过之前的文件了。

不过我这里倒是没有报错，仅仅是报无效的密码。可以确定密码没有输入错误。

**Comment by D0n9X1n** [comment]
密码错,可以试试看加一个双引号,比如密码 `123`, 写成 `"123"`

**Comment by KnorienChang** [comment]
> 密码错,可以试试看加一个双引号,比如密码 `123`, 写成 `"123"`

依然如此，我尝试过数字、非数字、带双引号和不带双引号的各种情况。

**Comment by D0n9X1n** [comment]
> > 密码错,可以试试看加一个双引号,比如密码 `123`, 写成 `"123"`
> 
> 依然如此，我尝试过数字、非数字、带双引号和不带双引号的各种情况。

有重现的方式吗? 或者更详细的日志信息, 比如 hexo g 的时候打出来的日志. 或者给一个 URL 我能访问到的看一下具体的原因.

**Comment by KnorienChang** [comment]
> > > 密码错,可以试试看加一个双引号,比如密码 `123`, 写成 `"123"`
> > 
> > 
> > 依然如此，我尝试过数字、非数字、带双引号和不带双引号的各种情况。
> 
> 有重现的方式吗? 或者更详细的日志信息, 比如 hexo g 的时候打出来的日志. 或者给一个 URL 我能访问到的看一下具体的原因.

http://47.99.188.127
password: "mikemessi"
日志有点长，如果需要的话我再提供

**Comment by D0n9X1n** [comment]
你先 `npm update` 一下, 更新到最新的版本 `v2.0.10`, 然后 `hexo clean && hexo g && hexo s` 试试.

另外, 能说一下 hexo 的版本吗?

**Comment by KnorienChang** [comment]
> 你先 `npm update` 一下, 更新到最新的版本 `v2.0.10`, 然后 `hexo clean && hexo g && hexo s` 试试.
> 
> 另外, 能说一下 hexo 的版本吗?

我每次都是执行hexo clean && hexo generate && hexo server --debug和hexo clean && hexo generate --deploy，所以是clean过得。
以下是需要的信息
hexo: 3.8.0
hexo-cli: 1.1.0
hexo-blog-encrypt 已经是最新的了。
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ hexo-blog-encrypt@2.0.10
info All dependencies
└─ hexo-blog-encrypt@2.0.10
✨  Done in 3.43s.

**Comment by D0n9X1n** [comment]
因为我看到你的那个文章, 密码输入框的标签 class 属性还是不带 hbe 前缀的, 应该是之前的几个版本的代码.
直接删掉 node_modules 文件夹下得 hexo-blog-encrypt,然后 `npm install` 一下试试.

输入密码的时候是有报错的, 原因是没有找到文章部分的 div id, 这个可能是和其他插件冲突, 或者其他原因没有能够解析到原文的内容.

**Comment by KnorienChang** [comment]
> 因为我看到你的那个文章, 密码输入框的标签 class 属性还是不带 hbe 前缀的, 应该是之前的几个版本的代码.
> 直接删掉 node_modules 文件夹下得 hexo-blog-encrypt,然后 `npm install` 一下试试.
> 
> 输入密码的时候是有报错的, 原因是没有找到文章部分的 div id, 这个可能是和其他插件冲突, 或者其他原因没有能够解析到原文的内容.

运行并没有报错。
删除node_modules文件夹重新安装依赖依然如此，就报错无效密码。

**Comment by D0n9X1n** [comment]
报错是在 开发者工具 -> `console` 里面.

**Comment by KnorienChang** [comment]
> 报错是在 开发者工具 -> `console` 里面.

console确实打印了错误日志，innerHTML错误。我不确定这是否是其他插件影响到了。

**Comment by D0n9X1n** [comment]
新版本的加密框附近的 class 都有 hbe 前缀:
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/3142935/47785279-35cd6280-dd43-11e8-8fcb-f8605a44a678.png">

我之前看到你的博客的时候, 是没有 hbe 前缀, 可能是版本问题. 

另外, 执行 hexo g 的时候也会有 Encrypt 的信息, 以供参考.
```
[0] % hexo g
INFO  Start processing
INFO  Encrypted the blog: encrypt-test  <- 
INFO  Files loaded in 229 ms
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: lib/blog-encrypt.js
INFO  Generated: fancybox/blank.gif
```

**Comment by KnorienChang** [comment]
Encrypted the blog这个日志确实是有的。但是依然密码对不上。如果这行日志没有出现的话，整个插件都是应该失效的吧。

**Comment by D0n9X1n** [comment]
是的, 说明没有触发加密逻辑.

**Comment by KnorienChang** [comment]
等我把这个主题改完配合你调试一下，现在用的这个主题貌似作者不怎么维护了，虽然能跑起来但是很多插件都报错或者无法使用。
