### ISSUE TITLE
请问 abstract字段能够添加图片的么？

### ISSUE THREAD

**Issue by gnailJC** [MikeCoder/hexo-blog-encrypt#53]
请问一下 abstract字段能够添加图片么，就是在首页显示效果是一张图片，而不是“Welcome to my blog, enter password to read.”这样的字段？？

**Comment by xiazeyu** [comment]
您可以尝试以html格式书写abstract字段
图片如:
```html
<img src=balabala />
```

也可以直接使用Emoji.

**Comment by 690677532** [comment]
好的，我试试，谢谢
