### ISSUE TITLE
使用archer主题，文章加密后会改变网页上方的字体大小

### ISSUE THREAD

**Issue by I-mpossible** [MikeCoder/hexo-blog-encrypt#54]
archer主题加密后，进入加密文章，上面的文章标题，wordcount等字体会变小，左上角打开侧边栏的按钮也会变形
archer主题在[这里](https://github.com/fi3ework/hexo-theme-archer)

**Comment by D0n9X1n** [comment]
Try `npm update` first.
Then, try `hexo clean && hexo g && hexo s`.

**Comment by I-mpossible** [comment]
> Try `npm update` first.
> Then, try `hexo clean && hexo g && hexo s`.

I tried. It doesn't work.

**Comment by littleNA** [comment]
这个对template.html的修改会导致错误。具体如下：
template.html中div id为"security"被修改成了"hbe-security"，当输入正确的密码时，blog-encrypt.js文件解密后找不id为"security”的div（第49行），进而导致报密码错误，此时密码输入框和解密后的文章同时显示。
