### ISSUE TITLE
ci: CI & Checker

### ISSUE THREAD

**Issue by xiazeyu** [MikeCoder/hexo-blog-encrypt#57]
安利一波CI和检查器

### [codeclimate](https://codeclimate.com/)
- 可以自动检测`eslint`, `fixme`, `markdownlint` ~还有神奇代码质量分析~
- 可以参考我另外一个项目的配置文件 https://github.com/xiazeyu/live2d-widget.js/blob/dev/.codeclimate.yml

## [TravisCI](https://www.travis-ci.org/)
- Linter没过的话可以打个红叉..
- 甚至可以丧心病狂的搭一个虚拟hexo站点然后用headless模拟跑测试~(有生之年)~, **以后**hexo更新了也会更加方便的看到能否支持
- **以后**增加test或者用ES6重构的话差pr的错或者commit的错会方便点(但愿没有)
- https://github.com/xiazeyu/live2d-widget.js/blob/dev/.travis.yml

## [markdownlint](https://www.npmjs.com/package/markdownlint)
- 也许可以让markdown更加整齐?
- https://github.com/xiazeyu/live2d-widget.js/blob/dev/.mdlrc

**Comment by D0n9X1n** [comment]
LGTM

顺便预祝高考顺利！
