### ISSUE TITLE
How to encrypt TOC under NexT theme

### ISSUE THREAD

**Issue by yuyuforest** [MikeCoder/hexo-blog-encrypt#58]
It is said that TOC can be encrypted in `themes/next/layout/_macro/sidebar.swig`.
However, after I used another one's code [hexo博文加密](http://zealscott.com/posts/46721/) , there is some bug in the TOC of encrypted article.
I want the presentation like this [Hexo Blog Encrypt](https://mhexo.github.io/example-site/2016/10/26/HexoBlogEncrpyt/) . How can I make it?

**Comment by yuyuforest** [comment]
**10/18/2018**
I just found the way to solve the problem. I will write a blog about it and put it here later.

**10/19/2018**
Now I finish the blog !
[Hexo | 在NexT主题下加密文章和目录](https://yuyuforest.com/2018/10/18/encrypt-toc/)

**Comment by D0n9X1n** [comment]
Cool~

**Comment by yuhldr** [comment]
更新一下 `NexT version 8.10.1`


这个文件：`node_modules/hexo-theme-next/layout/_macro/sidebar.njk`

这一行

```js
{%- set toc = toc(page.content, {class: 'nav', list_number: page.toc.number, max_depth: page.toc.max_depth}) %}
```

修改为

```js
{%- if page.encrypt == true %}
    {%- set toc = toc(page.origin, {class: 'nav', list_number: page.toc.number, max_depth: page.toc.max_depth}) %}
{% else %}
    {%- set toc = toc(page.content, {class: 'nav', list_number: page.toc.number, max_depth: page.toc.max_depth}) %}
{%- endif %}
```

其实原理就是：

如果加密了，生成目录 `toc` 变量就不能用 `page.content` 了，需要改为 `page.origin`

**Comment by gz0124** [comment]
`node_modules`？
