### ISSUE TITLE
如何加密TOC

### ISSUE THREAD

**Issue by NoahDragon** [MikeCoder/hexo-blog-encrypt#6]
https://github.com/hexojs/hexo/issues/2218

Encrypt TOC是否也可用此插件实现呢？

**Comment by D0n9X1n** [comment]
最新的 1.1.8 版本已经实现了。

可以查看：[https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc](https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc)

**Comment by NoahDragon** [comment]
多谢~
