### ISSUE TITLE
使用插件之后图片显示不了

### ISSUE THREAD

**Issue by jiangliuyang1999** [MikeCoder/hexo-blog-encrypt#60]
## Expected Behavior 
```markdown
![](img/file.png)
```
本应该显示放在img文件夹下的图片

## Actual Behavior
但是却只有一条横线

## Steps to Reproduce the Problem
在使用这个模块之前，图片显示是没问题的，加上之后就显示不了。再把这个模块unable之后又显示正常了。
## Specifications
(The version of the project, operating system, hardware etc.)
window10 系统，正常的网上教学配置 node.js 和 hexo。硬件层面应该是没问题的。

**Comment by D0n9X1n** [comment]
解密之后，看看文件的路径，应该是文件路径的问题，到时候写路径的时候，写上对应的相对路径或者绝对路径应该就可以。
比如 `<... src="img/file.png">` 不显示，但是直接访问 `http://xx.com/a/img/file.png` 就显示。把 `![](img/file.png)` 改成 `![](/a/img/file.png)` 或者 `![](http://xx.com/a/img/file.png)`。

**Comment by jaingmengmeng** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    Mike        您好！我已收到您的邮件。        感谢你的回复，问题已经解决了，很棒的插件，感谢你的付出。        祝好！2018-12-3
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1804226997
                            
                    
                        
                            
                                    
                                    1804226997@qq.com
                                    
                                    
                                    
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    在2018年12月3日 19:53，Mike<notifications@github.com> 写道： 


解密之后，看看文件的路径，应该是文件路径的问题，到时候写路径的时候，写上对应的相对路径或者绝对路径应该就可以。

比如 <... src="img/file.png"> 不显示，但是直接访问 http://xx.com/a/img/file.png 就显示。把 ![](img/file.png) 改成 ![](/a/img/file.png) 或者 ![](http://xx.com/a/img/file.png)。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
