### ISSUE TITLE
加一个MD5加密方式

### ISSUE THREAD

**Issue by ibrucekong** [MikeCoder/hexo-blog-encrypt#61]
考不考虑增加MD5加密方式，明码看着太难受

**Comment by D0n9X1n** [comment]
MD5 摘要原文中的话
没必要，如果是要保密的文章，也不会放在公开的代码库中，所以除了自己没人看到，而且明码方便查询。
解密的话，因为直接是前端解密，也不存在网络请求暴露密码的情况。

MD5 摘要原文的话
因为 MD5 是信息摘要，无法反向复原，所以不存在 MD5 加密一说。

**Comment by xiazeyu** [comment]
他的意思我觉得应该是指MD5存密码，加密解密用MD5后的密码做秘钥。不过MD5还是比较脆弱的，强度不一定比原密码高，属于那种只防君子不防小人的做法。不知道Mike你会怎么认为在前端解密失败时MD5一下再重试

**Comment by D0n9X1n** [comment]
这个实现到没什么问题，就是感觉意义不大。如果文章里面存的是密钥的话，如果是那种每篇文章都是不一样的密码，很难全部记住啊，到时候就看到一堆的密钥，还要反向找密码。
不过这样就可以用各种奇葩字符来做密码了。这样的话，用 Base64 搞一把是不是更好。
