### ISSUE TITLE
使用插件，解密后，博客左侧目录没了

### ISSUE THREAD

**Issue by YasyaKarasu** [MikeCoder/hexo-blog-encrypt#62]
在使用本插件解密以后，next主题的gemini左侧的目录没了。
本来应该是这样的：
![应该是这样](https://s1.ax1x.com/2018/12/01/Fnd4Rs.png)
有文章目录和站点概况
只有没有分大小标题的文章才会只有站点概况
而如果使用了这款插件，那么即使有分大小标题，也只有站点概况
![如下](https://s1.ax1x.com/2018/12/01/Fnd5zn.png)
我估计是因为解密前是不分大小标题的，所以就不加载了
请问可以解决吗

**Comment by D0n9X1n** [comment]
应该是 TOC，可以参考这个修改下模板：[对 TOC 进行加密](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E5%AF%B9-toc-%E8%BF%9B%E8%A1%8C%E5%8A%A0%E5%AF%86)

**Comment by stevenjoezhang** [comment]
这个插件本身不会加密文章目录，即使设置了对TOC进行加密，也只是`display:hidden`，查看html源代码就可以看到。这个功能似乎是鱼与熊掌不可兼得。
