### ISSUE TITLE
 Consider preventing brute force cracking?

### ISSUE THREAD

**Issue by darkduckgo** [MikeCoder/hexo-blog-encrypt#63]
## Expected Behavior 
期望不允许连续或者很多次的暴力破解密码

## Actual Behavior
目前好像这一块是空的, 很简单就能暴力去破解.因为密码一般也不会很复杂.5位以内全字符组合都不多

## Steps to Reproduce the Problem
 1. 最简单的实现,可以考虑加一个js的限制.虽然这样可能也只能防君子, 防不了小人
 2. 防止不了可以考虑有什么方式去触发一个邮件提醒机制, 或者获取对方ip之类的

**Comment by D0n9X1n** [comment]
1、暴力破解问题无解，只能尝试使用冗长复杂的密码。
2、邮件提醒的话，只有前端代码无解。js 浏览器发 http/https 请求的话，除非有自己的后端服务否则无解。如果调用 mailto 协议的话，会唤起本地邮件客户端，使用者直接关掉就行。
3、使用流量监控软件，比如 matomo 就可以看到访问过该页面的人，以及停留的时间和具体的操作。

可行的方案的话，只有直接写 cookie。限制输入次数。
