### ISSUE TITLE
图片lazyload加载的问题

### ISSUE THREAD

**Issue by lushuangning** [MikeCoder/hexo-blog-encrypt#66]
我在一个页面里添加了20张图片，格式是
```
![](https://xxxxxxxx/201806262.JPG)
```
解密后，只显示了前5张图片，后面的图片全都是空白

我查看了下网页代码，发现这些空白的图片全部变成了
```
<img src="/images/placeholder.png" alt="" data-src="https://xxx/2018062616.JPG" class="lazyload">
```

是不是因为懒加载导致了这些图片无法显示？

请问插件有没有针对该问题的解决方法

**Comment by kentsx** [comment]
问题情况相似。网页代码变成了（xxxx部分为我的实际域名）
```
<img src="data:image/png;base64,xxxxxxxxxxxx" data-original="https://xxxxxx" alt="hexoencrypt" title="xxxxxxxxxxx">
```
但我的图片完全没能载出来，是和我的路径中有中文有关吗？

**Comment by D0n9X1n** [comment]
@lushuangning 如果是懒加载的话，是需要手动再触发一次加载逻辑，代码可以加在这个之前：
https://github.com/MikeCoder/hexo-blog-encrypt/blob/9d2107c604f372570b67bcb2f3d94c775c598d19/lib/blog-encrypt.js#L57

具体的加载逻辑代码根据主题来，比较麻烦。目前针对这种情况没有好的解决办法。只能自己去主题代码里找代码添加。

**Comment by D0n9X1n** [comment]
@kentsx 能提供一个可以测试的文本嘛？
