### ISSUE TITLE
Archer主题解密后TOC依旧不显示（已按手册修改）

### ISSUE THREAD

**Issue by Cpresident** [MikeCoder/hexo-blog-encrypt#67]
查阅了所有关于TOC的issues，按照如下方式修改article.ejs文件

> 如果你想对 TOC 也进行加密，则在 article.ejs 中将 TOC 的生成代码修改成如下：
    <% if(post.toc == true){ %>
        <div id="toc-div" class="toc-article" <% if (post.encrypt == true) { %>style="display:none" <% } %>>
            <strong class="toc-title">Index</strong>
            <% if (post.encrypt == true) { %>
                <%- toc(post.origin) %>
            <% } else { %>
                <%- toc(post.content) %>
            <% } %>
        </div>
    <% } %>
    <%- post.content %>
然后使用 hexo clean && hexo g && hexo s，来查看效果。

Arch解密后TOC依旧不显示。

archer主题：https://github.com/fi3ework/hexo-theme-archer

修改article.ejs后如下
```
<article id="<%= post.layout %>-<%= post.slug %>" class="article article-type-<%= post.layout %>" itemscope itemprop="blogPost">
  <div class="article-meta">
    <%- partial('post/date', {class_name: 'article-date', date_format: null}) %>
    <%- partial('post/category') %>
  </div>
  <div class="article-inner">
    <%- partial('post/gallery') %>
    <% if (post.link || post.title){ %>
      <header class="article-header">
        <%- partial('post/title', {class_name: 'article-title'}) %>
      </header>
    <% } %>
    <div class="article-entry" itemprop="articleBody">
      <% if (post.excerpt && index){ %>
        <%- post.excerpt %>
        <% if (theme.excerpt_link){ %>
          <p class="article-more-link">
            <a href="<%- url_for(post.path) %>#more"><%= theme.excerpt_link %></a>
          </p>
        <% } %>
      <% } else { %>
            <% if(post.toc == true){ %>
        <div id="toc-div" class="toc-article" <% if (post.encrypt == true) { %>style="display:none" <% } %>>
            <strong class="toc-title">Index</strong>
            <% if (post.encrypt == true) { %>
                <%- toc(post.origin) %>
            <% } else { %>
                <%- toc(post.content) %>
            <% } %>
        </div>
    <% } %>
    <%- post.content %>
      <% } %>
    </div>
    <footer class="article-footer">
      <a data-url="<%- post.permalink %>" data-id="<%= post._id %>" class="article-share-link"><%= __('share') %></a>
      <% if (post.comments && config.disqus_shortname){ %>
        <a href="<%- post.permalink %>#disqus_thread" class="article-comment-link"><%= __('comment') %></a>
      <% } %>
      <%- partial('post/tag') %>
    </footer>
  </div>
  <% if (!index){ %>
    <%- partial('post/nav') %>
  <% } %>
</article>

<% if (!index && post.comments && config.disqus_shortname){ %>
<section id="comments">
  <div id="disqus_thread">
    <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  </div>
</section>
<% } %>
```

**Comment by D0n9X1n** [comment]
hexo g 时候的日志贴一下。

最好贴上你的博客的链接。如果不加密，TOC 可以正常显示吗？

**Comment by D0n9X1n** [comment]
archer 主题是在 layout.ejs 里面.

代码在 [这](https://github.com/fi3ework/hexo-theme-archer/blob/605f4368330bc1c5d4ad029864a39d9aec1b47f0/layout/layout.ejs#L27)

把这边的代码改成:

```
    <!-- toc -->
    <% if(is_post() && theme.toc) { %>
    <div class="toc-wrapper" style=
    <%- partial('_partial/intro-height', {attr: 'top'}) %>
    >
        <div class="toc-catalog">
            <span class="iconfont-archer catalog-icon">&#xe613;</span><span>CATALOG</span>
        </div>
        <% if (page.encrypt) { %>
            <div id="toc-div" style="display:none">
        <% } else { %>
            <div id="toc-div">
        <% } %>
            <% if (page.encrypt) { %>
            <%- toc(page.origin, {class: 'toc', list_number: true}) %>
            <% } else { %>
            <%- toc(page.content, {class: 'toc', list_number: true}) %>
            <% } %>
        </div>
    </div>
    <% } %>
    <div class="back-top iconfont-archer">&#xe639;</div>
```

**Comment by Cpresident** [comment]
> archer 主题是在 layout.ejs 里面.
> 
> 代码在 [这](https://github.com/fi3ework/hexo-theme-archer/blob/605f4368330bc1c5d4ad029864a39d9aec1b47f0/layout/layout.ejs#L27)
> 
> 把这边的代码改成:
> 
> ```
>     
>     <% if(is_post() && theme.toc) { %>
>     <div class="toc-wrapper" style=
>     <%- partial('_partial/intro-height', {attr: 'top'}) %>
>     >
>         <div class="toc-catalog">
>             <span class="iconfont-archer catalog-icon">&#xe613;</span><span>CATALOG</span>
>         </div>
>         <% if (page.encrypt) { %>
>             <div id="toc-div" style="display:none">
>         <% } else { %>
>             <div id="toc-div">
>         <% } %>
>             <% if (page.encrypt) { %>
>             <%- toc(page.origin, {class: 'toc', list_number: true}) %>
>             <% } else { %>
>             <%- toc(page.content, {class: 'toc', list_number: true}) %>
>             <% } %>
>         </div>
>     </div>
>     <% } %>
>     <div class="back-top iconfont-archer">&#xe639;</div>
> ```

小白非常感谢大佬！
