### ISSUE TITLE
加密文章需要刷新之后才能正确访问

### ISSUE THREAD

**Issue by Kasumisty** [MikeCoder/hexo-blog-encrypt#69]
你好，我使用的是diaspora主题，第一次点开加密文章的时候就算密码正确也不能进入，必须刷新一次之后输入密码才能进入，跪求解答

**Comment by D0n9X1n** [comment]
应该是外部依赖的JS文件没有加载完成。

**Comment by D0n9X1n** [comment]
Try v2.0.11

**Comment by Kasumisty** [comment]
尝试了一下还是没有解决这个问题

**Comment by frogcode1024** [comment]
我也遇到到了这个问题，请问最后解决了吗

**Comment by D0n9X1n** [comment]
这个问题是因为主题的机制导致的，从主页进行访问的时候，并不会完整加载文章页面的内容。

建议去主题的 repo 问一下，如何加载文章自定义的 js。
