### ISSUE TITLE
更新到最1.1.8版本,还是出错了...

### ISSUE THREAD

**Issue by ghost** [MikeCoder/hexo-blog-encrypt#7]
![image](https://cloud.githubusercontent.com/assets/13367924/20244813/5e1011c4-a9ca-11e6-8e63-0ae267f49c82.png)
- 用的是next主题,配置都设置没错了,之前成功过一次,但是第二次执行`hexo  g`就出错了,而且出错信息有时还不一样,,,

- 还有一个问题,就是 加密后的文章打开后,无法显示文章目录
![image](https://cloud.githubusercontent.com/assets/13367924/20244853/413ee370-a9cc-11e6-88aa-a6687cd405b3.png)

-再次是 密码输入正确后还是会出现密码错误提示框

**Comment by D0n9X1n** [comment]
修改配置之后，最好是用 `hexo clean && hexo g` 试试。

**Comment by D0n9X1n** [comment]
因为最新的版本中，已经把目录默认为隐藏 [https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc](https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc)

看报错信息像是 hexo 本身的异常， hexo-util 这个依赖包这个插件没有用到，建议提 issue 到 hexo 库里，看下。或者把其他的报错信息也截图放出来看下。

**Comment by ghost** [comment]
恩,我再琢磨一下,谢谢了,现在又能用了,,,
