### ISSUE TITLE
电脑浏览器输入密码时重叠

### ISSUE THREAD

**Issue by LiYanan2004** [MikeCoder/hexo-blog-encrypt#70]
## Actual Behavior
![image](https://user-images.githubusercontent.com/37542129/54470871-b79dc400-47ea-11e9-8c1d-0aca6ae6e28c.png)

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
浏览器型号？ 插件版本？有效信息过少。
