### ISSUE TITLE
使用插件后文章内的图片放大功能失效

### ISSUE THREAD

**Issue by artofwar344** [MikeCoder/hexo-blog-encrypt#71]
没有使用密码的文章单机图片是有放大浏览功能的，使用插件后文章内的图片放大功能失效

**Comment by D0n9X1n** [comment]
已知问题，任何有附加行为的效果，都会消失。你可以针对主题的代码，在 https://github.com/MikeCoder/hexo-blog-encrypt/blob/9d2107c604f372570b67bcb2f3d94c775c598d19/lib/blog-encrypt.js#L73 后加入图片放大的逻辑。
