### ISSUE TITLE
no responding

### ISSUE THREAD

**Issue by yuchen97** [MikeCoder/hexo-blog-encrypt#72]
Why do I sometimes enter a password and then click on the Enter page without responding?

**Comment by D0n9X1n** [comment]
Known issue. See #18 

The plugin depends on a external js file: `//cdn.bootcss.com/jquery/1.11.3/jquery.min.js`. If your theme already contains jquery, you can remove it from the template. Follow steps by: https://github.com/MikeCoder/hexo-blog-encrypt#change-template

**Comment by yuchen97** [comment]
I haven't tried this method yet, but when I use google chrome to access your test blog, this is also the problem. Entering the password and pressing Enter does not respond.
https://mhexo.github.io/example-site/2016/10/26/HexoBlogEncrpyt/

**Comment by yuchen97** [comment]
我现在解决了，我在这里
https://cdnjs.com/libraries/jquery/1.11.3
找了之前的渲染版本，他的链接貌似做了改动。
我将template里
```
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
```
改成下面这个
```
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
```
就ok了
