### ISSUE TITLE
暗黑模式

### ISSUE THREAD

**Issue by LiYanan2004** [MikeCoder/hexo-blog-encrypt#74]
最新版本插件，在material-x主题的暗黑模式配色下显示不太正常
网页背景为深色时提示的字体能否显示为白色？
![985045FE-2F81-4F49-B010-C65E937FD410](https://user-images.githubusercontent.com/37542129/54821589-9d2d8400-4cdd-11e9-8bde-b7c2d7779206.jpeg)

## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
参考：[修改加密模版](https://github.com/MikeCoder/hexo-blog-encrypt/blob/master/ReadMe.zh.md#%E4%BF%AE%E6%94%B9%E5%8A%A0%E5%AF%86%E6%A8%A1%E6%9D%BF)

可以在此基础上，在 div 上添加自己喜欢的 font-color 等 css 属性。

css 相关参考 [W3School](http://www.w3school.com.cn/web/web_css.asp) 或者 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Getting_started)。
