### ISSUE TITLE
启用文章加密后，字数统计不准确

### ISSUE THREAD

**Issue by cooper-q** [MikeCoder/hexo-blog-encrypt#76]

**Comment by cooper-q** [comment]
![image](https://user-images.githubusercontent.com/19221882/54976380-27733200-4fd5-11e9-8ea1-91479fe0b0d9.png)

**Comment by cooper-q** [comment]
本文字数应该是430 不知道是否有解决方法

**Comment by D0n9X1n** [comment]
无法通过修改 `hexo-blog-encrypt` 插件解决。

如果你对主题或者字数插件比较熟悉，可以参考这个方式：https://github.com/MikeCoder/hexo-blog-encrypt#encrypt-toc

将 Count 字数的逻辑修改为通过 post.encrypt 判断，如果为 true，则 Count(post.origin) 对象。否则就是 Count(post.content).

由于 Scope 不在本插件，就不继续讨论了。

**Comment by cooper-q** [comment]
谢谢提供资料
