### ISSUE TITLE
Can use for hexo-admin plugin

### ISSUE THREAD

**Issue by anhdhbn** [MikeCoder/hexo-blog-encrypt#79]
## Expected Behavior 
Expected that this plugin would work in conjunction with hexo-admin when I use hexo-admin plugin, I can edit those posts

## Actual Behavior
when use hexo-admin plugin to edit posts, i pressed enter but It doesn't work 

## Steps to Reproduce the Problem

Remove pass when use hexo-admin plugin or fix "enter key" isn't working

**Comment by D0n9X1n** [comment]
Hi, looks like hexo-admin didn't load other plugin's js files in posts. 
Which means hexo-blog-encrypt can do nothing for this issue.

You can add a issue to hexo-admin, wishing them to allow loading js files in posts.
