### ISSUE TITLE
加密不成功

### ISSUE THREAD

**Issue by SportPlusX** [MikeCoder/hexo-blog-encrypt#8]
加密未成功，问题会出现在哪里？安装`hexo-blog-encrypt`成功，启用，字段，hexo g 都有了。

**Comment by D0n9X1n** [comment]
最好是 hexo clean && hexo g， 可以的话，贴一下 hexo g 的 log

**Comment by SportPlusX** [comment]
hexo clean && hexo g 来一遍，然后重新 hexo s 解决了，谢谢
