### ISSUE TITLE
"Incorrect password"

### ISSUE THREAD

**Issue by waynia** [MikeCoder/hexo-blog-encrypt#80]
你好，感谢你开发的插件~我刚刚试用了一下，觉得还不错，唯一的问题是我设置了一个密码后，发现上传后输入这个密码，Chrome浏览器会提示“Incorrect Password”。

我知道这个问题其他人也应该遇到过，所以去翻看了所有的closed issue，不过发现和他们的情况似乎不一样。我用到的是最新版的Hexo-blog-encrypt插件，所以应该不是版本太低的问题。

不知道提供的有效信息会不会太少，期待你的回复，谢谢~

**Comment by D0n9X1n** [comment]
最好是在报错的时候打开 console 看看报错信息，并且提供一下。目前还是没办法确认问题所在。

**Comment by waynia** [comment]
> 最好是在报错的时候打开 console 看看报错信息，并且提供一下。目前还是没办法确认问题所在。

谢谢，刚刚在Console里看了一下，提示是：

Error: No content to display!
    at decryptAES (blog-encrypt.js:26)
    at HTMLInputElement.document.getElementById.onkeypress (blog-encrypt.js:124)

**Comment by D0n9X1n** [comment]
你是不是没有在博客添加内容啊？
hexo new 之后直接 hexo g && hexo s 看效果呢？

**Comment by waynia** [comment]
> 你是不是没有在博客添加内容啊？
> hexo new 之后直接 hexo g && hexo s 看效果呢？

哈哈，是的，谢谢提醒，原来提交空白文章会出现这种情况。

这个是我的问题，不过我想提一个小建议，“Incorrect Password”这个提示不能反映真实情况，建议fix一下这个提示；或者在ReadMe里给一个不要写空文章的tip~

**Comment by D0n9X1n** [comment]
是的，谢谢！

**Comment by D0n9X1n** [comment]
Fix by v2.1.1
