### ISSUE TITLE
vexo主题使用这个插件后 article-banner的base64编码背景图片没有加载

### ISSUE THREAD

**Issue by meerci** [MikeCoder/hexo-blog-encrypt#81]
## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications
(The version of the project, operating system, hardware etc.)

**Comment by D0n9X1n** [comment]
非常抱歉，不是很了解 Vue.js。看描述像 Vue.js 在解析图片的时候是在页面加载完成之后，而解密并没有触发渲染逻辑。可以尝试去掉 base64 图修改为资源文件形式。如果不行，只能 <img> 标签硬编码进去。

不清楚是否能通过后续添加钩子函数实现该问题。
