### ISSUE TITLE
文章加密内容中使用了其他插件加密后无法加载对应插件库文件？？？

### ISSUE THREAD

**Issue by 0428** [MikeCoder/hexo-blog-encrypt#82]
今天升级了next 7.1，我在一篇加密文章中除了有文字还使用hexo-tag-aplayer这个插件，当输入密码访问文章时，控制台提示aplayer未定义，很显然对应的aplyer.js和aplayer.css未引入，查看了源码的确没有引入。而不加密文章时能正常引入文件并且能正常显示音乐播放器。所以问题好像是如果使用了文章加密，进入到输入密码的界面时aplayer对应的js和css文件不会被加载，所以密码输入后，文字能正常显示而对应的插件由于没有引入js文件而无法加载出来。但是此前在next 5.x中没有出现该问题。我也试过重装这两个插件，好像还是没有效果，所以是什么原因呢。

**Comment by D0n9X1n** [comment]
看描述是因为加密的内容没有加载。稳妥起见你可以把这两个文件的资源链接放到 next 模版中，而不是文章里。同时，也需要添加后续的触发函数，因为解密之后，并不会执行 window.onload 函数，如果有钩子，会造成无法运行。
添加方式可以参考：https://github.com/MikeCoder/hexo-blog-encrypt#callback
触发函数可以咨询下 hexo-tag-aplayer 插件作者。

不过，如果主题或者其他插件覆盖了 window.onload 函数，可能会造成加密插件无法使用的情况，这种情况需要联系相关作者修改其他主题，或者插件。
