### ISSUE TITLE
显示不全

### ISSUE THREAD

**Issue by ghost** [MikeCoder/hexo-blog-encrypt#85]
为什么我的消息提示和错误弹窗和期望的不一样呢？

![捕获](https://user-images.githubusercontent.com/47672657/57821769-53848580-77c4-11e9-9f8a-f0c4ddecfc1c.PNG)

**Comment by D0n9X1n** [comment]
你有没有修改过模版？有的话，把新的模版发上来看看。

**Comment by ghost** [comment]
的确，我改过模板了，这是主题作者给出的办法
[hexo-theme-inside 添加文章加密](https://github.com/elmorec/hexo-theme-inside/issues/63)
我按照改过后能进行验证，就是提示语没能正确显示

**Comment by D0n9X1n** [comment]
Console 有没有报错？

简单点的修改的话，就直接把模版里面的 {{message}} 改成你要的文字。不通过配置进行修改了。

**Comment by ghost** [comment]
解决了，谢谢😜
