### ISSUE TITLE
能否加入cookie判断是否最近访问过

### ISSUE THREAD

**Issue by LiYanan2004** [MikeCoder/hexo-blog-encrypt#87]
输入正确的密码成功访问以后，5分钟内不用再输密码

**Comment by LiYanan2004** [comment]
我测试了下，还是有点问题，具体表现在：
我有 2 篇加密的博客，在一篇里输入正确的密码后到另一篇中会直接提示密码错误。
这个 cookie 应该有个 path 的选项，能否设置一下，cookie 仅对某一个页面起作用，谢谢开发者！

**Comment by D0n9X1n** [comment]
Thanks~
