### ISSUE TITLE
带前缀0密码报错

### ISSUE THREAD

**Issue by du33169** [MikeCoder/hexo-blog-encrypt#88]
v2.1.1
当密码为纯数字且开头为0，如0123，编译后即使输入正确密码仍然提示错误。
双引号可以解决问题。
含有非数字也可以。

**Comment by D0n9X1n** [comment]
这是 YAML 的缺陷，无法通过插件解决。因为不含双引号的数字，默认为 int 型，会自动将头部 0 去掉。可以加双引号或者通过强制类型转换解决。
<img width="488" alt="image" src="https://user-images.githubusercontent.com/3142935/58380220-38deb780-7fe1-11e9-914e-a23c19c4f704.png">
