### ISSUE TITLE
與Next模板兼容問題

### ISSUE THREAD

**Issue by cogitoxin** [MikeCoder/hexo-blog-encrypt#9]
當在Next模板使用加密功能的時候，頁面外觀會產生變化。比如：https://cogitoxin.github.io/2016/11/17/Death%20of%20Philosophy/

是需要另外設置嗎？

**Comment by D0n9X1n** [comment]
页面外观指的是多了那个输入框吗？我在和其他页面的比较下，只看到了这个的不同。

如果是想修改这个加密后的页面，可以在文章那边对[模板进行设置](https://github.com/MikeCoder/hexo-blog-encrypt#change-template)。

**Comment by zhuwenbing** [comment]
插件默认的样式将next主题的样式改变了，可以通过自定义template解决

**Comment by Pasc99** [comment]
非常感谢作者做出这么优秀的插件！我个人用的也是NEXT主题，要解决不兼容的话，最简单的方法是在_config.yml中加入default_template，复制内容：[作者说明文档](https://github.com/MikeCoder/hexo-blog-encrypt#change-template)，并删除
```
                    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
                    <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
                    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
                    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
```
这样就不会改变原来的NEXT页面风格了。当然大神们也可以自定义模板。
@cogitoxin

**Comment by cogitoxin** [comment]
謝謝！

**Comment by xmeng1** [comment]
+1

**Comment by D0n9X1n** [comment]
跟新代码到 v2.0.* 版本。解决了这个问题。
