### ISSUE TITLE
明文密码会在公开的静态文件暴露

### ISSUE THREAD

**Issue by Matthew-Han** [MikeCoder/hexo-blog-encrypt#92]
假设我为了实现多设备同步更新blog，将source、theme这些静态文件push到新分支上，所有的post.md均可以在该分支上浏览，而加密的文章也会暴露password，可以在`/_posts/加密的文章.md`里看到。
当然完全是可以把静态文件作为单独private的repository，但是为了方便我就作为了单独的分支并公开。
可以更新加密加盐的插件使得暴露的只是加密后的密码？

**Comment by D0n9X1n** [comment]
不好实现，hexo 的插件本质上都是在 `source/xxx.md ===> public/xxx.html` 这个渲染过程中通过钩子函数进行操作，不会修改 xxx.md 。

建议新建 private repository 吧。
