### ISSUE TITLE
密码错误问题"Incorrect password"

### ISSUE THREAD

**Issue by JietingHuang** [MikeCoder/hexo-blog-encrypt#94]
我第一次用的时候没什么问题，hexo d 之后也是正常情况。  
但是后面有一次部署之后发现不正常了，前后一天之隔，  
第二天输入正确密码 后一直报"Incorrect password"，我就来查看了issue，
我确保update之后，hexo clean再去测试发现还是没用，密码换了两三个去  
用还是"Incorrect password"，控制台信息如下：  
blog-encrypt.js:47 TypeError: Cannot read property 'html' of null
    at decryptAES (blog-encrypt.js:35)
    at HTMLInputElement.document.getElementById.onkeypress (blog-encrypt.js:199)
decryptAES @ blog-encrypt.js:47
document.getElementById.onkeypress @ blog-encrypt.js:199
blog-encrypt.js:83 TypeError: Cannot read property 'html' of null
    at decryptAES (blog-encrypt.js:48)
    at HTMLInputElement.document.getElementById.onkeypress (blog-encrypt.js:199)

**Comment by D0n9X1n** [comment]
你有没有修改过模板？

给一个可以测试的链接过来看看。

**Comment by JietingHuang** [comment]
没有修改过模板，直接伸手用🙏    
重点是刚开始用一点问题都没有，才过一天就出问题了，博客刚搭建的
https://jietinghuang.github.io/JietingHuang.github.io/2019/08/05/hello-world/
谢谢了！

**Comment by JietingHuang** [comment]
对了，密码是123q

**Comment by D0n9X1n** [comment]
你是不是改过主题？

如果博客只是简单的静态内容的话，直接把 https://github.com/MikeCoder/hexo-blog-encrypt/blob/338c4b9259bbdf182699d296c0982c9cb53fc969/lib/blog-encrypt.js#L35 这一行改为 `document.getElementById("encrypt-blog").innerHTML = content;` 应该就可以了。

**Comment by JietingHuang** [comment]
good job ，3Q
