### ISSUE TITLE
为什么要Base64包裹

### ISSUE THREAD

**Issue by xiazeyu** [MikeCoder/hexo-blog-encrypt#96]
RT
会导致密文尺寸更大

**Comment by D0n9X1n** [comment]
这个提交：https://github.com/MikeCoder/hexo-blog-encrypt/commit/cf3447b769207cae08fdb80ed9cbe4e75a83ba87

引入的 Base64, 当 content 包含有特殊字符的时候，AES 加密会异常，用 Base64 是为了保证加密内容为可识别内容。

**Comment by xiazeyu** [comment]
特殊字符..是指什么
能被UTF-8表示吗

**Comment by D0n9X1n** [comment]
emmmmm,年代久远。。已经忘了异常 case 了 😂

先去掉吧，遇到有问题再说。
