### ISSUE TITLE
主页面abstract无法正常显示

### ISSUE THREAD

**Issue by jcool98** [MikeCoder/hexo-blog-encrypt#97]
主页面显示内容乱码：
点击此处输入正确密码即可阅读本篇文章~ Incorrect Password! No content to display! U2FsdGVkX1/LQqIz0eVxf6cDR1E6q56KrGhTg03dOheZnGy1TxZ57wq9OE0Z1Ukmo ...

config_yml中的配置：
    default_abstract: 该篇文章博主不想让其他人看见哟~
    default_message: 点击此处输入正确密码即可阅读本篇文章~

**Comment by D0n9X1n** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/3142935/63500758-0cadd680-c4fd-11e9-9e7d-36d8732500e4.png">

<img width="751" alt="image" src="https://user-images.githubusercontent.com/3142935/63500698-ea1bbd80-c4fc-11e9-811b-65622dfefc9d.png">

<img width="646" alt="image" src="https://user-images.githubusercontent.com/3142935/63500803-27804b00-c4fd-11e9-9070-124a0ecbea9e.png">

多个主题都无法重现。需要更多信息。

**Comment by jcool98** [comment]
点进去的页面message显示没有问题， 显示在博客主页的abstract乱码

**Comment by xiazeyu** [comment]
能提供一个theme或者源码吗

**Comment by JiangnanCai** [comment]
我现在用的是[hiero](https://github.com/iTimeTraveler/hexo-theme-hiero)这个主题，也遇到了这个问题。
在主界面的加密文章，摘要部分会显示乱码。
![屏幕快照 2020-07-30 上午7 35 01](https://user-images.githubusercontent.com/33519231/88885161-41133200-d238-11ea-95e2-fb05c27fca86.png)
