### ISSUE TITLE
Break changes

### ISSUE THREAD

**Issue by xiazeyu** [MikeCoder/hexo-blog-encrypt#98]
# 可能的Breaking changes

## 配置名称更改

例如

> default_template => defaultTemplate(内容会被更改)
> default_message => defaultPrompt
> (new) defaultWrongPassword
> (delete) enable => (undefined)
> (delete) callback(现在所有的js都会被执行)

等

好处

- 强行让老用户阅读Breaking changes(滑稽)
- 使用更适合前端规范的 驼峰命名法
- 优化API逻辑

使用旧API时进行提示

## 依赖

由`Crypto-js`换为`Crypto(Nodejs)`以及`window.crypto+Encoder(WebAPI)`. 

具体为: 使用Pbkdf2进行key derivation(UTF8转换为AES所需的key和iv), 使用HMAC做verify(确保博客内容为原作者所写, 未被篡改), 使用AES256(CBC)进行加密, 全程使用Encoder进行解码处理(UTF8 String与ArrayBuffer互转)

> https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto
> https://nodejs.org/dist/latest-v12.x/docs/api/crypto.html

好处: 
- 巨少的代码大小
- 现在只需导入一个js和一个css了
- 更详细的异常处理(密码错误, 解密失败, 验证失败(但是能显示失败内容))
- 支持异步了, 意味着巨量内容的解码不会卡死整个网页
- 现在高级用户可以自己提供key和iv了...

坏处: 
- IE全系不支持
- 老浏览器不支持

**Comment by D0n9X1n** [comment]
Ok！

为了避免更新出现异常，第一个版本可以做一个原命名的校验，如果是原配置名称也能使用，但是 hexo g 给个 warning、过一个月再来一个版本切换。

**Comment by D0n9X1n** [comment]
hexo 的 _config.yml 还是维持下划线的命名风格，和 hexo 原风格一致。插件内部可以转驼峰。
