### ISSUE TITLE
启用scroll_to_more: true之后，无法打开全文

### ISSUE THREAD

**Issue by Psychiwave** [MikeCoder/hexo-blog-encrypt#99]
# Issue
启用scroll_to_more: true之后，无法打开全文
网页url会添加#more
去掉#more后可以正常输入密码打开全文
 
post的头是这样的：
```
---
title: 网上冲浪
categories: 
password: xxxxxx
abstract: 这篇文章已被加密，咳咳。(打开后去掉'#more')
message: 打不开打不开打不开～
abbrlink: wscl
---
```

**Comment by xiazeyu** [comment]
`scroll_to_more`是哪个插件提供的?
能给个链接吗

**Comment by Psychiwave** [comment]
> `scroll_to_more`是哪个插件提供的?
> 能给个链接吗

应该是next自带的
> themes/next/layout/_macro/post.swig    
貌似是这个地址

**Comment by xiazeyu** [comment]
我主页增加了#more还是可以正常打开原文的啊orz

看看控制台有没有什么其他的异常?

**Comment by Psychiwave** [comment]
> 我主页增加了#more还是可以正常打开原文的啊orz
> 
> 看看控制台有没有什么其他的异常?

我试了下用原始的next主题，发现确实不是这个插件的问题。233我注释掉一点代码之后现在暂时好了，谢啦～
